# -*- coding: utf-8 -*-
"""APP.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ysyxe-efvKwoto7zQAMT7ozkWe9DnZFH
"""

# -*- coding: utf-8 -*-
"""APP.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ysyxe-efvKwoto7zQAMT7ozkWe9DnZFH
"""

# -*- coding: utf-8 -*-
"""APP.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ysyxe-efvKwoto7zQAMT7ozkWe9DnZFH
"""

import os
import io
import json
import math
import re
import random
import time
import base64
import threading
from typing import List, Optional

import requests
from requests.adapters import HTTPAdapter, Retry
import polyline
import pydeck as pdk
import streamlit as st
import streamlit.components.v1 as components
from PIL import Image, ImageDraw
from dotenv import load_dotenv

# New in this feature: nearby-amenities uses only the stdlib + requests above.
# The ADAS Collision Watch tab additionally needs `ultralytics` (YOLOv8) for
# on-device object detection -- install with `pip install ultralytics`. It is
# imported lazily inside load_yolo_model() so the rest of the app still runs
# fine if that package isn't installed.

load_dotenv()

# Shared session with automatic retries/backoff for transient network errors
# on OpenRouteService / Wikipedia. Nominatim gets its own, gentler handling
# below because hammering an already-429'd geocoder with more retries just
# makes things worse.
_session = requests.Session()
_retry = Retry(
    total=3, backoff_factor=0.5,
    status_forcelist=[500, 502, 503, 504],
    allowed_methods=["GET", "POST"],
)
_session.mount("https://", HTTPAdapter(max_retries=_retry))
_session.mount("http://", HTTPAdapter(max_retries=_retry))

# --- Nominatim rate limiting -------------------------------------------------
# Nominatim's usage policy caps free public usage at ~1 request/second per
# client, and hosts that share an outbound IP (Streamlit Community Cloud,
# Colab, etc.) can trip that limit even when THIS app is well-behaved,
# because *other* apps on the same IP are also calling it. We enforce our
# own >=1.1s gap between calls, and fall back to Photon (a free, keyless
# OSM-data mirror run by Komoot) if Nominatim itself is throttling us.
_nominatim_lock = threading.Lock()
_last_nominatim_call = [0.0]
_NOMINATIM_MIN_INTERVAL_S = 1.1

GEOAPIFY_URL = "https://api.geoapify.com/v1/geocode/search"

PHOTON_URL = "https://photon.komoot.io/api/"

ORS_DIRECTIONS_URL_TMPL = "https://api.openrouteservice.org/v2/directions/{profile}/geojson"
NOMINATIM_URL = "https://nominatim.openstreetmap.org/search"
WIKI_API = "https://en.wikipedia.org/w/api.php"
OPEN_METEO_URL = "https://api.open-meteo.com/v1/forecast"

# WMO weather codes (used by Open-Meteo) collapsed into plain descriptions.
_WMO_CODE_DESC = {
    0: "clear sky", 1: "mainly clear", 2: "partly cloudy", 3: "overcast",
    45: "fog", 48: "depositing rime fog",
    51: "light drizzle", 53: "drizzle", 55: "dense drizzle",
    61: "light rain", 63: "rain", 65: "heavy rain",
    71: "light snow", 73: "snow", 75: "heavy snow",
    80: "light rain showers", 81: "rain showers", 82: "violent rain showers",
    95: "thunderstorm",
}

REQUEST_HEADERS = {"User-Agent": "MapQuestSuite/1.0 (educational demo project)"}

PROFILES = {
    "Driving": "driving-car",
    "Cycling": "cycling-regular",
    "Walking": "foot-walking",
}

AVOID_OPTIONS_BY_PROFILE = {
    "driving-car": {"Highways": "highways", "Tolls": "tollways", "Ferries": "ferries"},
    "cycling-regular": {"Ferries": "ferries", "Steps": "steps"},
    "foot-walking": {"Ferries": "ferries", "Steps": "steps"},
}

# Context presets for the one-tap mode picker -- maps a mood/need to a full
# bundle of routing settings so the person doesn't have to configure each
# slider/checkbox individually (decision-fatigue removal).
CONTEXT_PRESETS = {
    "🏃 In a rush": {
        "mode": "Driving", "avoid": [], "base_g": 120, "elev_g": 1.5, "stop_g": 15,
    },
    "😴 Tired / conserve energy": {
        "mode": "Driving", "avoid": ["Highways"], "base_g": 100, "elev_g": 3.0, "stop_g": 25,
    },
    "🚶 Exploring / no rush": {
        "mode": "Walking", "avoid": [], "base_g": 0, "elev_g": 0.0, "stop_g": 0,
    },
}

# Rough, editable cost assumptions for the multi-modal cost optimizer.
# These are NOT live fares -- free routing APIs don't expose real-time
# rideshare/transit pricing -- they're transparent, adjustable estimates so
# people can compare modes on the same trip.
COST_ASSUMPTIONS = {
    "driving-car": {"label": "🚗 Driving", "per_km": 8.0, "flat_fee": 0.0},
    "cycling-regular": {"label": "🚲 Cycling (own bike)", "per_km": 0.0, "flat_fee": 0.0},
    "foot-walking": {"label": "🚶 Walking", "per_km": 0.0, "flat_fee": 0.0},
}

# ORS maneuver 'type' codes that correspond to a stop / yield / signal point.
STOP_LIKE_MANEUVER_TYPES = {0, 1, 2, 3, 4, 5, 7, 8, 9, 12, 13}

# --- Nearby amenities (hotels / restaurants / restrooms) ---------------------
# Sourced from OpenStreetMap via the free, keyless Overpass API -- the same
# open dataset already used elsewhere in this app (geocoding fallbacks). OSM
# records *locations*, not live prices, so any 'fee'/'charge' tag found on a
# venue is surfaced as-is (variable, source-reported); everything else falls
# back to a flat, editable estimate that's clearly labeled as an assumption.
OVERPASS_URL = "https://overpass-api.de/api/interpreter"

AMENITY_CATEGORIES = {
    "🏨 Hotels": {"osm_key": "tourism", "osm_value": "hotel", "color": [155, 40, 200, 200]},
    "🍽️ Restaurants": {"osm_key": "amenity", "osm_value": "restaurant", "color": [255, 140, 0, 200]},
    "🚻 Restrooms": {"osm_key": "amenity", "osm_value": "toilets", "color": [0, 140, 210, 200]},
}

# Flat, user-editable fallback prices (INR) used only when OSM itself has no
# price-carrying tag for a given venue -- which is the common case, since OSM
# is a map database, not a live pricing feed.
DEFAULT_PRICE_ASSUMPTIONS = {
    "🏨 Hotels": 1500.0,       # per night, budget/mid-range guess
    "🍽️ Restaurants": 300.0,   # per meal, casual-dining guess
    "🚻 Restrooms": 0.0,       # most public restrooms are free unless tagged otherwise
}

# --- ADAS: Collision Watch (CV + optional VLM) + Voice Route Assistant ------
# CV step: YOLOv8n (ultralytics), runs locally, free, no API key -- flags
# vehicles/cyclists/pedestrians by how large & centered they are in one
# still frame (webcam snapshot or uploaded photo), NOT a live video feed.
# VLM step: optional, needs the user's own ANTHROPIC_API_KEY -- sends the
# same frame + CV summary to Claude vision for a plain-language hazard read.
ANTHROPIC_MESSAGES_URL = "https://api.anthropic.com/v1/messages"
DEFAULT_VLM_MODEL = "claude-sonnet-5"

# COCO class names YOLOv8 can output that are relevant to a collision check.
COLLISION_RELEVANT_CLASSES = {"person", "bicycle", "car", "motorcycle", "bus", "train", "truck"}

# Risk level -> (label, Streamlit banner fn name, box/text color)
RISK_LEVELS = {
    0: {"label": "🟢 Safe -- no close objects detected", "color": (0, 170, 0)},
    1: {"label": "🟡 Caution -- object nearby", "color": (220, 190, 0)},
    2: {"label": "🟠 Warning -- object close and ahead", "color": (255, 140, 0)},
    3: {"label": "🔴 Collision risk -- object very close and centered", "color": (220, 30, 30)},
}

# Thresholds on (fraction of frame area the box covers, how far the box's
# center is from the frame's horizontal center as a fraction of width).
# Deliberately simple/transparent -- a real ADAS uses calibrated camera
# geometry and depth, not just 2D box size, so treat this as illustrative.
_RISK_AREA_HIGH = 0.35
_RISK_AREA_MED = 0.15
_RISK_AREA_LOW = 0.05
_RISK_CENTER_TIGHT = 0.25
_RISK_CENTER_LOOSE = 0.35

# Simple phrase patterns for pulling a destination out of a spoken command,
# e.g. "navigate to Puri" -> "Puri". Falls back to using the whole utterance
# as the destination if nothing matches.
_VOICE_DEST_PATTERNS = [
    r"navigate to (.+)", r"directions to (.+)", r"take me to (.+)",
    r"route to (.+)", r"how do i get to (.+)", r"how far is (.+)",
    r"distance to (.+)", r"drive to (.+)", r"go to (.+)",
]


def get_ors_key() -> str:
    try:
        if "ORS_API_KEY" in st.secrets:
            return st.secrets["ORS_API_KEY"]
    except Exception:
        pass
    return os.getenv("ORS_API_KEY", "")


def get_geoapify_key() -> str:
    """Optional. If set, Geoapify (free tier, 3000 req/day, no card) becomes
    the PRIMARY geocoder, since Nominatim's shared free endpoint gets
    rate-limited on cloud hosts regardless of how careful this app is."""
    try:
        if "GEOAPIFY_API_KEY" in st.secrets:
            return st.secrets["GEOAPIFY_API_KEY"]
    except Exception:
        pass
    return os.getenv("GEOAPIFY_API_KEY", "")


def get_anthropic_key() -> str:
    """Optional. Only needed for the VLM hazard-read step in the ADAS
    Collision Watch tab -- the CV/YOLO detection itself needs no API key."""
    try:
        if "ANTHROPIC_API_KEY" in st.secrets:
            return st.secrets["ANTHROPIC_API_KEY"]
    except Exception:
        pass
    return os.getenv("ANTHROPIC_API_KEY", "")


def safe_json(resp: requests.Response, source: str) -> dict:
    try:
        return resp.json()
    except Exception:
        snippet = resp.text[:200].replace("\n", " ") if resp.text else "(empty body)"
        raise RuntimeError(f"{source} returned a non-JSON response (HTTP {resp.status_code}): {snippet}")


# ============================================================
# Shared helpers
# ============================================================

class RouteResult:
    """
    Plain class with an explicit __init__ (deliberately NOT a @dataclass).
    Some deployment/build pipelines strip decorators they don't recognize,
    which silently turns a dataclass into a bare class with no generated
    __init__ -- and calling it with keyword arguments then raises
    'RouteResult() takes no arguments'. Writing __init__ by hand avoids
    that failure mode entirely, at the cost of a few extra lines.
    """

    def __init__(
        self,
        summary: str,
        distance_m: float,
        duration_s: float,
        duration_in_traffic_s: Optional[float],
        stop_count: int,
        polyline_points: List[List[float]],
        encoded_polyline: str,
        elevation_profile: Optional[List[float]] = None,
        elevation_gain_m: float = 0.0,
        co2_grams: float = 0.0,
        origin_country: Optional[str] = None,
        destination_country: Optional[str] = None,
        steps: Optional[List[dict]] = None,
    ):
        self.summary = summary
        self.distance_m = distance_m
        self.duration_s = duration_s
        self.duration_in_traffic_s = duration_in_traffic_s
        self.stop_count = stop_count
        self.polyline_points = polyline_points
        self.encoded_polyline = encoded_polyline
        self.elevation_profile = elevation_profile if elevation_profile is not None else []
        self.elevation_gain_m = elevation_gain_m
        self.co2_grams = co2_grams
        self.origin_country = origin_country
        self.destination_country = destination_country
        # Turn-by-turn maneuvers from ORS, e.g.
        # [{"instruction": "Turn right onto MG Road", "distance_m": 240.0, "duration_s": 35.0}, ...]
        # ORS is asked for `"instructions": True` (see _fetch_single_route) but until this
        # field was added nothing on RouteResult ever kept that data around -- every step
        # past distance/duration/stop-count silently threw the actual directions away.
        self.steps = steps if steps is not None else []

    @property
    def is_international(self) -> bool:
        return bool(
            self.origin_country
            and self.destination_country
            and self.origin_country != self.destination_country
        )


def _throttled_nominatim_get(params: dict) -> requests.Response:
    """Enforce our own >=1.1s gap before hitting Nominatim, since the shared
    cloud IP may already be close to its rate limit from other apps."""
    with _nominatim_lock:
        elapsed = time.monotonic() - _last_nominatim_call[0]
        if elapsed < _NOMINATIM_MIN_INTERVAL_S:
            time.sleep(_NOMINATIM_MIN_INTERVAL_S - elapsed)
        resp = requests.get(NOMINATIM_URL, params=params, headers=REQUEST_HEADERS, timeout=15)
        _last_nominatim_call[0] = time.monotonic()
        return resp


def _geocode_photon(place: str) -> Optional[tuple]:
    """Fallback geocoder: free, keyless, OSM-data mirror. Used only when
    Nominatim itself is rate-limiting us, not as a first choice."""
    try:
        resp = _session.get(PHOTON_URL, params={"q": place, "limit": 1},
                             headers=REQUEST_HEADERS, timeout=15)
        data = safe_json(resp, "Photon geocoding")
        features = data.get("features", [])
        if not features:
            return None
        feat = features[0]
        lng, lat = feat["geometry"]["coordinates"]
        country = feat.get("properties", {}).get("country")
        return float(lat), float(lng), country
    except Exception:
        return None


def _geocode_geoapify(place: str, api_key: str) -> Optional[tuple]:
    try:
        resp = _session.get(GEOAPIFY_URL, params={"text": place, "limit": 1, "apiKey": api_key},
                             headers=REQUEST_HEADERS, timeout=15)
        data = safe_json(resp, "Geoapify geocoding")
        features = data.get("features", [])
        if not features:
            return None
        props = features[0].get("properties", {})
        lat, lng = props.get("lat"), props.get("lon")
        if lat is None or lng is None:
            return None
        return float(lat), float(lng), props.get("country")
    except Exception:
        return None


_PINCODE_RE = re.compile(r"\b(\d{6})\b")  # Indian PIN codes are exactly 6 digits


def extract_pincode(text: str) -> Optional[str]:
    """Pulls a 6-digit Indian PIN code out of a free-text address, if present."""
    match = _PINCODE_RE.search(text)
    return match.group(1) if match else None


def haversine_km(lat1: float, lng1: float, lat2: float, lng2: float) -> float:
    R = 6371.0
    phi1, phi2 = math.radians(lat1), math.radians(lat2)
    dphi = math.radians(lat2 - lat1)
    dlambda = math.radians(lng2 - lng1)
    a = math.sin(dphi / 2) ** 2 + math.cos(phi1) * math.cos(phi2) * math.sin(dlambda / 2) ** 2
    return 2 * R * math.asin(math.sqrt(a))


@st.cache_data(ttl=3600, show_spinner=False)
def _geocode_pincode_india(pincode: str) -> Optional[tuple]:
    """Best-effort centroid lookup for an Indian PIN code via Nominatim's
    structured search. Deliberately NOT used as the primary geocoder -- a
    PIN code's centroid is far less precise than a full place name -- it
    exists only to sanity-check a free-text geocode result below."""
    try:
        resp = _throttled_nominatim_get({
            "postalcode": pincode, "country": "India",
            "format": "json", "limit": 1, "addressdetails": 1,
        })
        results = safe_json(resp, "Nominatim PIN code lookup")
        if results:
            r = results[0]
            return float(r["lat"]), float(r["lon"]), r.get("address", {}).get("country")
    except Exception:
        pass
    return None


# How far (km) a free-text geocode result is allowed to land from its own
# stated PIN code's centroid before we distrust it. India's PIN code areas
# are typically a few km to a few tens of km across; 100km gives headroom
# for large rural PIN codes while still catching "wrong continent" misses.
_PINCODE_MISMATCH_KM = 100.0


@st.cache_data(ttl=3600, show_spinner=False)
def _geocode_chain(place: str) -> tuple:
    """Returns (lat, lng, country_name_or_None). Cached for 1h since a given
    place name always resolves to the same point.

    Provider order:
      1. Geoapify (if GEOAPIFY_API_KEY is configured) -- free tier, keyed,
         not subject to the shared-IP throttling that hits Nominatim on
         cloud hosts. This is the recommended primary provider.
      2. Nominatim, self-throttled to >=1.1s between calls.
      3. Photon (Komoot's free, keyless OSM mirror) as a last resort.
    """
    geoapify_key = get_geoapify_key()
    if geoapify_key:
        result = _geocode_geoapify(place, geoapify_key)
        if result is not None:
            return result
        # Geoapify failed for some reason -- fall through to the free chain
        # rather than giving up immediately.

    try:
        resp = _throttled_nominatim_get(
            {"q": place, "format": "json", "limit": 1, "addressdetails": 1}
        )
        if resp.status_code == 429:
            raise RuntimeError("Nominatim rate-limited us (429)")
        results = safe_json(resp, "Nominatim geocoding")
        if results:
            result = results[0]
            country = result.get("address", {}).get("country")
            return float(result["lat"]), float(result["lon"]), country
    except Exception:
        pass  # fall through to Photon below

    # Nominatim failed or rate-limited us -- try the Photon mirror instead
    # of failing outright.
    fallback = _geocode_photon(place)
    if fallback is not None:
        return fallback

    raise RuntimeError(f"Could not geocode '{place}' -- try a more specific place name.")


POSTAL_PINCODE_API = "https://api.postalpincode.in/postoffice/{}"


@st.cache_data(ttl=3600, show_spinner=False)
def lookup_pincodes_for_name(locality: str) -> List[dict]:
    """Free, keyless lookup of Indian post offices matching a locality name,
    straight from India Post's own records -- NOT a geocoder, no lat/lng
    fuzzy matching involved at all. Returns a list of
    {name, district, state, pincode} dicts (empty if no match/on error)."""
    if not locality.strip():
        return []
    try:
        resp = _session.get(
            POSTAL_PINCODE_API.format(locality.strip()),
            headers=REQUEST_HEADERS, timeout=15,
        )
        data = safe_json(resp, "India Post PIN lookup")
        if not data or data[0].get("Status") != "Success":
            return []
        return [
            {
                "name": po.get("Name"),
                "district": po.get("District"),
                "state": po.get("State"),
                "pincode": po.get("Pincode"),
            }
            for po in (data[0].get("PostOffice") or [])
        ]
    except Exception:
        return []


def _guess_locality_and_district(place: str) -> tuple:
    """Splits 'Balaji Greens, Sambalpur, India' into ('Balaji Greens',
    'Sambalpur') -- a simple heuristic: first comma-segment is assumed to
    be the specific locality, second is assumed to be the city/district."""
    parts = [p.strip() for p in place.split(",") if p.strip()]
    locality = parts[0] if parts else place.strip()
    district = parts[1] if len(parts) > 1 else None
    return locality, district


def auto_derive_pincode(place: str) -> Optional[str]:
    """Attempts to find a single, unambiguous PIN code for a place name via
    India Post records alone -- no user-supplied PIN, no geocoder. Returns
    None (rather than guessing) if the locality name is too common/ambiguous
    across multiple districts, since a wrong auto-guess would be worse than
    no guess."""
    locality, district = _guess_locality_and_district(place)
    matches = lookup_pincodes_for_name(locality)
    if not matches:
        return None
    if district:
        narrowed = [m for m in matches if district.lower() in (m.get("district") or "").lower()]
        if narrowed:
            matches = narrowed
    pincodes = {m["pincode"] for m in matches if m.get("pincode")}
    return next(iter(pincodes)) if len(pincodes) == 1 else None


def geocode(place: str) -> tuple:
    """Public geocoding entrypoint. Wraps _geocode_chain() with a PIN-code
    sanity check: if a 6-digit PIN is present in the input (typed by the
    user OR auto-derived from India Post records below) and the free-text
    geocode result lands implausibly far from that PIN code's own
    centroid, this is a strong signal the free-text query got hijacked by
    a same-named place elsewhere (a common failure mode for hyperlocal
    names like apartment complexes or small colonies) -- in that case we
    trust the PIN code centroid instead and flag it to the user."""
    primary = _geocode_chain(place)
    pincode = extract_pincode(place)
    auto_derived = False
    if not pincode:
        pincode = auto_derive_pincode(place)
        auto_derived = pincode is not None
    if not pincode:
        return primary

    pin_result = _geocode_pincode_india(pincode)
    if pin_result is None:
        return primary  # couldn't verify -- don't block on it

    pin_lat, pin_lng, pin_country = pin_result
    dist_km = haversine_km(primary[0], primary[1], pin_lat, pin_lng)
    if dist_km > _PINCODE_MISMATCH_KM:
        pin_source = f"auto-derived PIN code {pincode} (via India Post records)" if auto_derived \
            else f"its own stated PIN code ({pincode})"
        st.warning(
            f"⚠️ \"{place}\" geocoded {dist_km:.0f} km away from the area covered by its "
            f"{pin_source} -- likely a wrong-match on a hyperlocal name. "
            f"Using the PIN code's location instead."
        )
        return pin_lat, pin_lng, pin_country
    return primary


def compute_elevation_gain(profile: List[float]) -> float:
    gain = 0.0
    for prev, curr in zip(profile, profile[1:]):
        if curr - prev > 0:
            gain += curr - prev
    return gain


def circle_polygon(lat: float, lng: float, radius_m: float, n_points: int = 16) -> List[List[float]]:
    """Approximate a circle as a closed polygon ring [[lng, lat], ...] for avoid_polygons."""
    R = 6371000.0
    lat_rad = math.radians(lat)
    ring = []
    for i in range(n_points):
        angle = 2 * math.pi * i / n_points
        dlat = (radius_m * math.cos(angle)) / R
        dlng = (radius_m * math.sin(angle)) / (R * math.cos(lat_rad))
        ring.append([lng + math.degrees(dlng), lat + math.degrees(dlat)])
    ring.append(ring[0])
    return ring


def build_avoid_polygons(hazard_zones: List[dict]) -> Optional[dict]:
    if not hazard_zones:
        return None
    polygons = [[circle_polygon(z["lat"], z["lng"], z["radius_m"])] for z in hazard_zones]
    return {"type": "MultiPolygon", "coordinates": polygons}


def _fetch_single_route(
    coords_lnglat: List[List[float]], profile: str, preference: str,
    avoid_features: List[str], avoid_polygons: Optional[dict], ors_key: str,
) -> Optional[dict]:
    body = {
        "coordinates": coords_lnglat,
        "elevation": True,
        "instructions": True,
        "preference": preference,
    }
    options = {}
    if avoid_features:
        options["avoid_features"] = avoid_features
    if avoid_polygons:
        options["avoid_polygons"] = avoid_polygons
    if options:
        body["options"] = options

    url = ORS_DIRECTIONS_URL_TMPL.format(profile=profile)
    headers = {"Authorization": ors_key, "Content-Type": "application/json"}
    resp = _session.post(url, json=body, headers=headers, timeout=20)
    data = safe_json(resp, "OpenRouteService")
    if resp.status_code != 200:
        msg = data.get("error", {}).get("message", str(data))
        # ORS returns 2010 'routable point not found' / 2004 'unable to find
        # a route between points' when the profile can't bridge the gap --
        # most commonly because it would require crossing an ocean.
        if resp.status_code in (404, 500) and ("route" in msg.lower() or "point" in msg.lower()):
            raise RuntimeError(
                "No route found between these points for the selected travel mode. "
                "This usually means the two locations aren't connected by road/path/cycleway "
                "(e.g. they're on different continents separated by ocean, with no ferry link "
                "in the routing data). Try a route within the same landmass, or pick a "
                "different travel mode."
            )
        raise RuntimeError(f"OpenRouteService error: {msg}")
    features = data.get("features", [])
    return features[0] if features else None


def fetch_routes(
    waypoint_addresses: List[str], profile: str = "driving-car",
    avoid_features: Optional[List[str]] = None,
    hazard_zones: Optional[List[dict]] = None,
    ors_key: str = "",
) -> List[RouteResult]:
    avoid_features = avoid_features or []
    avoid_polygons = build_avoid_polygons(hazard_zones or [])

    coords_lnglat = []
    countries = []
    for addr in waypoint_addresses:
        lat, lng, country = geocode(addr)
        coords_lnglat.append([lng, lat])
        countries.append(country)

    origin_country = countries[0]
    destination_country = countries[-1]

    def _geocode_debug_lines() -> str:
        lines = []
        for addr, (lng, lat), country in zip(waypoint_addresses, coords_lnglat, countries):
            country_note = f", {country}" if country else " (country unknown)"
            lines.append(f"  \u2022 \"{addr}\" \u2192 ({lat:.5f}, {lng:.5f}){country_note}")
        return "  \n".join(lines)  # trailing double-space = markdown line break

    preferences = [("recommended", "Recommended route"), ("shortest", "Shortest route")]
    results = []
    seen_distances = set()
    for preference, label in preferences:
        try:
            feature = _fetch_single_route(coords_lnglat, profile, preference, avoid_features, avoid_polygons, ors_key)
        except RuntimeError as e:
            # Surface exactly where each address resolved to -- a wrong or
            # ambiguous geocode (e.g. a hyperlocal name matching a
            # similarly-named place on another continent) is the #1 cause
            # of "no route found" errors, and this makes that immediately
            # diagnosable instead of just confusing.
            raise RuntimeError(f"{e}\n\nGeocoded points:\n{_geocode_debug_lines()}")
        if feature is None:
            continue
        props = feature["properties"]
        summary = props.get("summary", {})
        distance_m = summary.get("distance", 0.0)

        rounded = round(distance_m, -2)
        if rounded in seen_distances:
            continue
        seen_distances.add(rounded)

        duration_s = summary.get("duration", 0.0)
        stop_count = 0
        steps = []
        for segment in props.get("segments", []):
            for step in segment.get("steps", []):
                if step.get("type") in STOP_LIKE_MANEUVER_TYPES:
                    stop_count += 1
                instruction = (step.get("instruction") or "").strip()
                if instruction:
                    steps.append({
                        "instruction": instruction,
                        "distance_m": step.get("distance", 0.0),
                        "duration_s": step.get("duration", 0.0),
                        "name": step.get("name", ""),
                    })

        coords = feature["geometry"]["coordinates"]
        points = [[c[1], c[0]] for c in coords]
        elevation_profile = [c[2] for c in coords if len(c) > 2]
        encoded = polyline.encode([(lat, lng) for lat, lng in points])

        r = RouteResult(
            summary=label, distance_m=distance_m, duration_s=duration_s,
            duration_in_traffic_s=None, stop_count=stop_count,
            polyline_points=points, encoded_polyline=encoded,
            elevation_profile=elevation_profile,
            origin_country=origin_country, destination_country=destination_country,
            steps=steps,
        )
        r.elevation_gain_m = compute_elevation_gain(elevation_profile)
        results.append(r)

    if not results:
        raise RuntimeError(
            f"No routes returned -- try different locations or fewer restrictions.\n\n"
            f"Geocoded points:\n{_geocode_debug_lines()}"
        )
    return results


def sample_points(points: List[List[float]], max_samples: int = 100) -> List[List[float]]:
    if len(points) <= max_samples:
        return points
    step = len(points) / max_samples
    return [points[int(i * step)] for i in range(max_samples)]


@st.cache_data(ttl=3600, show_spinner=False)
def wiki_geosearch(lat: float, lng: float, radius_m: int) -> list:
    """Nearby Wikipedia pages around a point. Cached since the same
    place+radius always returns the same nearby articles."""
    raw = _session.get(WIKI_API, params={
        "action": "query", "list": "geosearch", "gscoord": f"{lat}|{lng}",
        "gsradius": radius_m, "gslimit": 6, "format": "json",
    }, headers=REQUEST_HEADERS, timeout=15)
    resp = safe_json(raw, "Wikipedia geosearch")
    return resp.get("query", {}).get("geosearch", [])


@st.cache_data(ttl=3600, show_spinner=False)
def wiki_page_details(titles_pipe_joined: str) -> dict:
    """Extracts + thumbnails for a '|'-joined list of page titles. Cached
    per unique title set."""
    raw = _session.get(WIKI_API, params={
        "action": "query", "prop": "extracts|pageimages", "exintro": True,
        "explaintext": True, "piprop": "thumbnail", "pithumbsize": 400,
        "titles": titles_pipe_joined, "format": "json",
    }, headers=REQUEST_HEADERS, timeout=15)
    resp = safe_json(raw, "Wikipedia page details")
    return resp.get("query", {}).get("pages", {})


def truncate_at_word(text: str, max_len: int = 400) -> str:
    """Truncate to max_len chars without cutting a word in half."""
    if len(text) <= max_len:
        return text
    cut = text[:max_len].rsplit(" ", 1)[0]
    return cut + "..."


@st.cache_data(ttl=600, show_spinner=False)
def fetch_weather(lat: float, lng: float) -> Optional[dict]:
    """Current conditions at a point, via Open-Meteo (free, no API key).
    Cached for 10 min since weather doesn't need per-second freshness."""
    try:
        resp = _session.get(OPEN_METEO_URL, params={
            "latitude": lat, "longitude": lng,
            "current": "temperature_2m,wind_speed_10m,precipitation,weather_code",
            "timezone": "auto",
        }, headers=REQUEST_HEADERS, timeout=15)
        data = safe_json(resp, "Open-Meteo")
        current = data.get("current", {})
        if not current:
            return None
        code = current.get("weather_code")
        return {
            "temp_c": current.get("temperature_2m"),
            "wind_kmh": current.get("wind_speed_10m"),
            "precip_mm": current.get("precipitation"),
            "description": _WMO_CODE_DESC.get(code, "unknown conditions"),
        }
    except Exception:
        return None


# Thresholds for treating a sampled point as an active routing hazard, as
# opposed to just an advisory note. Deliberately stricter than
# weather_route_advice()'s thresholds -- we only want to spend a reroute on
# conditions that plausibly change which road is the right choice, not
# every point that's merely "a bit windy".
_HAZARD_ICE_MAX_TEMP_C = 2.0
_HAZARD_ICE_MIN_PRECIP_MM = 0.5
_HAZARD_WIND_KMH = 45.0
_HAZARD_HEAVY_PRECIP_MM = 4.0
_HAZARD_HEAT_C = 40.0
_HAZARD_ZONE_RADIUS_M = 900


def classify_weather_hazard(weather: dict) -> Optional[dict]:
    """Returns a single dominant hazard {"type", "note"} for one sampled
    point if conditions cross a routing-relevant threshold, else None.
    Checked in rough order of how dangerous/route-changing each is."""
    if not weather:
        return None
    temp = weather.get("temp_c")
    wind = weather.get("wind_kmh")
    precip = weather.get("precip_mm")

    if temp is not None and precip is not None and temp <= _HAZARD_ICE_MAX_TEMP_C and precip >= _HAZARD_ICE_MIN_PRECIP_MM:
        return {"type": "ice_risk", "note": f"possible icing ({temp:.0f}°C with active precipitation)"}
    if wind is not None and wind >= _HAZARD_WIND_KMH:
        return {"type": "high_wind", "note": f"high wind gusts (~{wind:.0f} km/h)"}
    if precip is not None and precip >= _HAZARD_HEAVY_PRECIP_MM:
        return {"type": "heavy_precip", "note": f"heavy precipitation ({precip:.1f} mm)"}
    if temp is not None and temp >= _HAZARD_HEAT_C:
        return {"type": "extreme_heat", "note": f"extreme heat ({temp:.0f}°C)"}
    return None


def sample_weather_hazards_along_route(points: List[List[float]], max_samples: int = 8) -> List[dict]:
    """Fetches (cached) weather at a handful of evenly-spaced points along a
    route and returns only the ones that cross a hazard threshold, each
    shaped like a hazard_zone entry so it can feed straight into
    build_avoid_polygons() alongside community-reported hazards."""
    sampled = sample_points(points, max_samples=max_samples)
    hazards = []
    for lat, lng in sampled:
        weather = fetch_weather(lat, lng)
        hazard = classify_weather_hazard(weather)
        if hazard:
            hazards.append({
                "lat": lat, "lng": lng, "radius_m": _HAZARD_ZONE_RADIUS_M,
                "type": hazard["type"], "note": hazard["note"],
            })
    return hazards


def explain_weather_reroute(baseline: RouteResult, alt: Optional[RouteResult], hazards: List[dict]) -> str:
    """Plain-English trade-off explanation -- this is the piece Google Maps
    itself doesn't surface: not just 'here's a route' but 'here's why we'd
    pick a different one than the fastest option right now'."""
    if not hazards:
        return "No active weather hazards detected along this route -- fastest route is also the weather-safe one."
    reasons = "; ".join(sorted({h["note"] for h in hazards}))
    if alt is None or alt.encoded_polyline == baseline.encoded_polyline:
        return (
            f"Detected {reasons} along the route, but no viable detour avoids it "
            f"(likely a single-road corridor) -- proceed with caution on the affected stretch."
        )
    extra_km = (alt.distance_m - baseline.distance_m) / 1000.0
    extra_min = (alt.duration_s - baseline.duration_s) / 60.0
    return (
        f"Rerouted around {reasons}. This costs **+{max(extra_km, 0):.1f} km / "
        f"+{max(extra_min, 0):.0f} min** versus the fastest route, in exchange for avoiding "
        f"the flagged hazard zone(s)."
    )


def estimate_mode_cost(profile: str, distance_m: float, duration_s: float) -> float:
    """Rough, transparent cost estimate for a mode -- NOT a live fare quote.
    Free routing APIs don't expose real-time rideshare/transit pricing."""
    cfg = COST_ASSUMPTIONS.get(profile, {"per_km": 0.0, "flat_fee": 0.0})
    return cfg["flat_fee"] + (distance_m / 1000.0) * cfg["per_km"]


def render_international_badge(route: RouteResult):
    if route.is_international:
        st.info(f"🌍 International route: **{route.origin_country} → {route.destination_country}**")


def _format_step_distance(distance_m: float) -> str:
    """Human-friendly distance for a single turn -- meters below 1 km,
    kilometers above it."""
    if distance_m >= 1000:
        return f"{distance_m / 1000:.1f} km"
    return f"{distance_m:.0f} m"


def render_turn_by_turn_directions(route: RouteResult, key_prefix: str = "", expanded: bool = False):
    """Displays the actual point-A-to-point-B, turn-by-turn directions for a
    route -- every stop-like maneuver ORS returns, in order, with the
    distance for that leg. Without this, a RouteResult only ever showed a
    single aggregate distance/duration; this is what was missing."""
    if not route.steps:
        st.caption("No turn-by-turn directions were returned for this route.")
        return
    with st.expander(f"🧭 Turn-by-turn directions ({len(route.steps)} steps)", expanded=expanded):
        lines = [
            f"{i}. {step['instruction']}  *({_format_step_distance(step['distance_m'])})*"
            for i, step in enumerate(route.steps, start=1)
        ]
        st.markdown("  \n".join(lines))


def directions_speech_text(route: RouteResult, destination: str, max_steps: int = 8) -> str:
    """Builds the sentence(s) spoken back by the browser's TTS: a short
    summary, then the actual turns (capped so the narration doesn't run on
    forever for long routes) -- rather than just distance/duration/turn
    *count* with no real directions in it."""
    dist_km = route.distance_m / 1000.0
    dur_min = route.duration_s / 60.0
    parts = [
        f"{destination} is {dist_km:.1f} kilometers away, about {dur_min:.0f} minutes."
    ]
    steps = route.steps[:max_steps]
    for i, step in enumerate(steps, start=1):
        parts.append(f"Step {i}: {step['instruction']}, for {_format_step_distance(step['distance_m'])}.")
    if len(route.steps) > max_steps:
        parts.append(f"Plus {len(route.steps) - max_steps} more steps -- see the screen for the full list.")
    return " ".join(parts)


@st.cache_data(ttl=1800, show_spinner=False)
def fetch_nearby_amenities(lat: float, lng: float, radius_m: int, categories: tuple) -> dict:
    """Nearby hotels/restaurants/restrooms around a point, from OpenStreetMap
    via the free, keyless Overpass API. Returns {category: [ {name, lat,
    lng, tags} ]}. Cached for 30 min since a given point+radius+category set
    always returns roughly the same nearby venues.

    `categories` must be a tuple (not a list) so it's hashable for st.cache_data.
    """
    results = {cat: [] for cat in categories}
    if not categories:
        return results

    clauses = []
    for cat in categories:
        cfg = AMENITY_CATEGORIES[cat]
        clauses.append(f'node["{cfg["osm_key"]}"="{cfg["osm_value"]}"](around:{radius_m},{lat},{lng});')
    overpass_ql = f"[out:json][timeout:20];({''.join(clauses)});out center 40;"

    try:
        resp = _session.post(OVERPASS_URL, data={"data": overpass_ql},
                              headers=REQUEST_HEADERS, timeout=25)
        data = safe_json(resp, "Overpass")
    except Exception:
        return results  # Overpass is a shared free service -- fail soft, not loud

    for el in data.get("elements", []):
        tags = el.get("tags", {})
        el_lat = el.get("lat") or el.get("center", {}).get("lat")
        el_lng = el.get("lon") or el.get("center", {}).get("lon")
        if el_lat is None or el_lng is None:
            continue
        for cat in categories:
            cfg = AMENITY_CATEGORIES[cat]
            if tags.get(cfg["osm_key"]) == cfg["osm_value"]:
                results[cat].append({
                    "name": tags.get("name", "Unnamed"),
                    "lat": el_lat, "lng": el_lng, "tags": tags,
                })
                break
    return results


def extract_price_info(category: str, tags: dict, default_estimate: float) -> tuple:
    """Returns (price_text, is_variable). `is_variable=True` means the price
    text came from an actual OSM tag on that venue (source-reported, so it
    varies venue-to-venue); `False` means it fell back to the flat, editable
    estimate -- always labeled '(assumed)' so it's never mistaken for a real
    quote."""
    charge_tag = tags.get("charge") or tags.get("cost")
    if charge_tag:
        return charge_tag, True

    if category == "🚻 Restrooms":
        fee_tag = tags.get("fee")
        if fee_tag == "no":
            return "Free", True
        if fee_tag == "yes":
            return "Fee charged (amount not listed)", True
        return (f"₹{default_estimate:.0f} (assumed)" if default_estimate > 0 else "Likely free (assumed)"), False

    if category == "🏨 Hotels":
        stars = tags.get("stars")
        if stars:
            multiplier = {"1": 0.6, "2": 0.8, "3": 1.0, "4": 1.6, "5": 2.5}.get(str(stars), 1.0)
            return f"₹{default_estimate * multiplier:.0f}/night (assumed, {stars}★)", False
        return f"₹{default_estimate:.0f}/night (assumed)", False

    # Restaurants (and anything else)
    price_range = tags.get("price_range")
    if price_range:
        return f"{price_range} (venue-reported range)", True
    return f"₹{default_estimate:.0f}/meal (assumed)", False


@st.cache_resource(show_spinner=False)
def load_yolo_model():
    """Loads YOLOv8n once per session. Returns None (rather than raising) if
    `ultralytics` isn't installed, so the tab can degrade gracefully instead
    of crashing the whole app. First call downloads ~6MB of weights."""
    try:
        from ultralytics import YOLO
    except ImportError:
        return None
    try:
        return YOLO("yolov8n.pt")
    except Exception:
        return None


def classify_collision_risk(area_frac: float, center_offset_frac: float) -> int:
    """Returns a risk level 0-3 from how much of the frame a detected object
    covers and how close its center is to the frame's horizontal center.
    A simple, transparent 2D proxy for proximity+heading -- not real depth
    estimation, which needs calibrated stereo/lidar camera geometry."""
    if area_frac > _RISK_AREA_HIGH and center_offset_frac < _RISK_CENTER_TIGHT:
        return 3
    if area_frac > _RISK_AREA_MED and center_offset_frac < _RISK_CENTER_LOOSE:
        return 2
    if area_frac > _RISK_AREA_LOW:
        return 1
    return 0


def run_collision_detection(image: Image.Image):
    """Runs YOLOv8n on one still frame. Returns (annotated_image,
    detections, overall_risk_label) or (None, [], None) if the detector
    isn't available or detection failed for any reason."""
    model = load_yolo_model()
    if model is None:
        return None, [], None

    try:
        img_w, img_h = image.size
        results = model.predict(image, verbose=False)[0]
        names = results.names

        annotated = image.convert("RGB").copy()
        draw = ImageDraw.Draw(annotated)
        detections = []
        overall_level = 0

        for box in results.boxes:
            cls_name = names.get(int(box.cls[0]), "object")
            if cls_name not in COLLISION_RELEVANT_CLASSES:
                continue
            conf = float(box.conf[0])
            x1, y1, x2, y2 = [float(v) for v in box.xyxy[0]]
            area_frac = ((x2 - x1) * (y2 - y1)) / (img_w * img_h)
            center_offset_frac = abs(((x1 + x2) / 2) - img_w / 2) / img_w

            risk_level = classify_collision_risk(area_frac, center_offset_frac)
            overall_level = max(overall_level, risk_level)
            risk_info = RISK_LEVELS[risk_level]

            draw.rectangle([x1, y1, x2, y2], outline=risk_info["color"], width=4)
            draw.text((x1 + 2, max(0, y1 - 14)), f"{cls_name} {conf:.0%}", fill=risk_info["color"])

            detections.append({
                "class": cls_name, "confidence": round(conf, 2),
                "risk_level": risk_level, "risk_label": risk_info["label"],
            })

        detections.sort(key=lambda d: d["risk_level"], reverse=True)
        return annotated, detections, RISK_LEVELS[overall_level]["label"]
    except Exception:
        return None, [], None


def describe_scene_with_vlm(image: Image.Image, detections: list, api_key: str, model: str) -> str:
    """Sends the same frame + CV summary to Claude vision for a short,
    plain-language hazard read -- the piece raw bounding boxes can't give:
    *interpretation* (e.g. 'pedestrian about to cross') rather than just
    labeled shapes."""
    buf = io.BytesIO()
    image.convert("RGB").save(buf, format="JPEG", quality=85)
    b64 = base64.b64encode(buf.getvalue()).decode("utf-8")

    det_summary = ", ".join(
        f"{d['class']} ({d['risk_label']})" for d in detections
    ) or "no vehicles, cyclists, or pedestrians detected by the CV model"

    prompt = (
        "You are a driver-assistance co-pilot looking at one forward-facing camera frame. "
        f"An object-detection model found: {det_summary}. In 2-3 short sentences, describe the "
        "immediate collision-relevant hazards a driver should know about right now, in plain, "
        "calm, urgent-if-needed language. Interpret the scene -- don't just restate the detection list."
    )
    body = {
        "model": model,
        "max_tokens": 300,
        "messages": [{
            "role": "user",
            "content": [
                {"type": "image", "source": {"type": "base64", "media_type": "image/jpeg", "data": b64}},
                {"type": "text", "text": prompt},
            ],
        }],
    }
    headers = {"x-api-key": api_key, "anthropic-version": "2023-06-01", "content-type": "application/json"}
    resp = _session.post(ANTHROPIC_MESSAGES_URL, json=body, headers=headers, timeout=30)
    data = safe_json(resp, "Anthropic VLM")
    if resp.status_code != 200:
        raise RuntimeError(f"Anthropic API error: {data.get('error', {}).get('message', str(data))}")
    return " ".join(c.get("text", "") for c in data.get("content", []) if c.get("type") == "text").strip()


def parse_voice_destination(text: str) -> str:
    """Pulls a destination out of a spoken command like 'navigate to Puri'
    -> 'Puri'. Falls back to treating the whole utterance as the
    destination if no known phrasing matches."""
    lowered = text.strip().lower()
    for pattern in _VOICE_DEST_PATTERNS:
        match = re.match(pattern, lowered)
        if match:
            return match.group(1).strip().rstrip("?.! ")
    return text.strip()


# ============================================================
# Streamlit page setup
# ============================================================

st.set_page_config(page_title="MapQuest Suite", layout="wide")
st.title("🗺️ MapQuest Suite")
st.caption(
    "One thesis, five demonstrations: mainstream mapping optimizes for distance and "
    "historical traffic, but stays silent on *why* a route is best, ignores live "
    "conditions until it's too late to matter, and treats every rider identically. "
    "Each tab below targets one specific, named gap -- built on free, no-credit-card APIs."
)

TAB_GAP_STATEMENTS = {
    "🌱 Greenest Route": "**Gap addressed -- Route Trade-Off Clarity:** rather than a single black-box "
                          "'recommended' route, this reroutes around live weather hazards and community-"
                          "reported closures, then explains the exact cost of that choice in km/min.",
    "👻 Ghost Jam Predictor": "**Gap addressed -- Delayed Real-Time Anomaly Routing:** mainstream apps react "
                              "to traffic after it forms from historical data; this models *why* phantom jams "
                              "emerge from following/braking behavior, which is predictive, not reactive.",
    "🕰️ AR Local History": "**Gap addressed -- Frictionless Discovery:** surfaces contextual, place-anchored "
                           "knowledge (historical/cultural context) that keyword-and-review search misses "
                           "entirely, without requiring a phone-camera AR view.",
    "📡 Offline Navigator": "**Gap addressed -- Connectivity Resilience:** most navigation assumes constant "
                            "connectivity; this shows a route can be compressed small enough to transmit over "
                            "SMS/Bluetooth for low-connectivity or emergency scenarios.",
    "🧘 Sensory & Safety Router": "**Gap addressed -- Precise, Personalized Guidance:** one-size-fits-all ETAs "
                                  "ignore that the same route can be a poor fit for a given person or time of "
                                  "day; this scores routes for sensory load and night-safety instead.",
    "🚨 ADAS Collision Watch & Voice Nav": "**Gap addressed -- Hands-Free, Hazard-Aware Driving:** mainstream "
                                           "maps don't watch the road or take spoken commands; this adds a "
                                           "CV+VLM collision-risk read on a live frame and a voice-driven route "
                                           "assistant, entirely separate concerns bolted onto the same routing core.",
}

ORS_KEY = get_ors_key()
ORS_KEY_MISSING_MSG = (
    "No ORS_API_KEY found. Get a free key (no card needed) at "
    "https://openrouteservice.org/dev/#/signup -- then locally put it in a .env file, "
    "or on Streamlit Community Cloud add it under Settings > Secrets as:\n"
    'ORS_API_KEY = "your_real_key_here"'
)
# Don't st.stop() the whole app here -- Tab 3 (AR Local History) only calls
# Wikipedia/Nominatim and works fine with no ORS key at all. Each
# ORS-dependent tab checks ORS_KEY itself before running.

if not get_geoapify_key():
    st.caption(
        "💡 Geocoding currently relies on Nominatim's free public endpoint, which can get "
        "rate-limited on shared cloud IPs (Streamlit Cloud, Colab, etc.). For reliable "
        "geocoding, get a free Geoapify key (no card, 3000 req/day) at "
        "https://www.geoapify.com/get-started-with-maps-api and add it as GEOAPIFY_API_KEY "
        "in Secrets or your .env file."
    )

if "hazard_zones" not in st.session_state:
    st.session_state.hazard_zones = []
if "community_notes" not in st.session_state:
    # Broader crowdsourced layer: only entries tagged "🚧 Hazard/Closure"
    # actually affect routing (mirrored into hazard_zones below); the rest
    # (lighting, accessibility, tips) are informational map pins only.
    st.session_state.community_notes = []

NOTE_CATEGORIES = {
    "🚧 Hazard/Closure": {"affects_routing": True, "color": [220, 30, 30, 200]},
    "💡 Broken lighting": {"affects_routing": False, "color": [255, 200, 0, 200]},
    "♿ Accessibility issue": {"affects_routing": False, "color": [30, 100, 220, 200]},
    "🎒 Local tip": {"affects_routing": False, "color": [30, 180, 90, 200]},
}

tab1, tab2, tab3, tab4, tab5, tab6 = st.tabs([
    "🌱 Greenest Route",
    "👻 Ghost Jam Predictor",
    "🕰️ AR Local History",
    "📡 Offline Navigator",
    "🧘 Sensory & Safety Router",
    "🚨 ADAS + Voice Nav",
])

# ============================================================
# TAB 1 -- Greenest Route Optimizer (advanced routing + hazard avoidance)
# ============================================================
with tab1:
    st.info(TAB_GAP_STATEMENTS["🌱 Greenest Route"])

    def _apply_context_preset():
        preset = CONTEXT_PRESETS.get(st.session_state.get("t1_preset"))
        if not preset:
            return
        st.session_state["t1_mode"] = preset["mode"]
        st.session_state["t1_avoid"] = preset["avoid"]
        st.session_state["t1_base"] = preset["base_g"]
        st.session_state["t1_elev"] = preset["elev_g"]
        st.session_state["t1_stop"] = preset["stop_g"]

    st.radio(
        "How are you traveling right now? (one-tap preset -- fills in mode + weights below; adjust anything afterward)",
        list(CONTEXT_PRESETS.keys()), index=None, horizontal=True,
        key="t1_preset", on_change=_apply_context_preset,
    )

    c1, c2 = st.columns(2)
    with c1:
        origin1 = st.text_input("Origin", value="Bhubaneswar, India", key="t1_origin", help="Tip: include a 6-digit PIN code (e.g. 'Balaji Greens, Sambalpur, 768004') for hyperlocal names -- the app cross-checks against the PIN code's area to catch wrong-match geocodes.")
    with c2:
        destination1 = st.text_input("Destination", value="Puri, India", key="t1_dest", help="Tip: include a 6-digit PIN code (e.g. 'Balaji Greens, Sambalpur, 768004') for hyperlocal names -- the app cross-checks against the PIN code's area to catch wrong-match geocodes.")

    with st.expander("🚗 Routing options"):
        mode_label = st.radio("Travel mode", list(PROFILES.keys()), horizontal=True, key="t1_mode")
        profile = PROFILES[mode_label]

        avoid_map = AVOID_OPTIONS_BY_PROFILE[profile]
        avoid_labels = st.multiselect("Avoid", list(avoid_map.keys()), key="t1_avoid")
        avoid_features = [avoid_map[label] for label in avoid_labels]

        waypoints_text = st.text_area(
            "Extra stops (optional, one per line, visited in order)",
            placeholder="e.g.\nChandaka Wildlife Sanctuary\nPipili",
            key="t1_waypoints",
        )

        st.caption("CO2 model weights (assumptions, not official emission factors)")
        wc1, wc2, wc3 = st.columns(3)
        with wc1:
            base_g_per_km = st.slider("g CO2 / km", 0, 250, 120, key="t1_base")
        with wc2:
            elevation_g_per_m = st.slider("g CO2 / m climbed", 0.0, 5.0, 1.5, key="t1_elev")
        with wc3:
            stop_g_per_stop = st.slider("g CO2 / stop", 0, 50, 15, key="t1_stop")

    with st.expander("📌 Community Notes (crowdsourced hazards, lighting, access, tips)"):
        st.caption(
            "A local-knowledge layer most mainstream mapping apps don't have: only **🚧 Hazard/Closure** "
            "notes actually reroute you around them; the rest are informational pins. "
            "Session-only for this demo -- not shared across users or saved between restarts."
        )
        nc1, nc2, nc3, nc4 = st.columns([3, 2, 1, 1])
        with nc1:
            note_place = st.text_input("Place name", key="note_place", label_visibility="collapsed", placeholder="Place name")
        with nc2:
            note_category = st.selectbox("Category", list(NOTE_CATEGORIES.keys()), key="note_category", label_visibility="collapsed")
        with nc3:
            note_radius = st.number_input("Radius (m)", 20, 20000, 300, key="note_radius", label_visibility="collapsed")
        with nc4:
            if st.button("Add", key="note_add"):
                try:
                    lat, lng, _ = geocode(note_place)
                    entry = {
                        "name": note_place, "lat": lat, "lng": lng,
                        "radius_m": note_radius, "category": note_category,
                    }
                    st.session_state.community_notes.append(entry)
                    if NOTE_CATEGORIES[note_category]["affects_routing"]:
                        st.session_state.hazard_zones.append(entry)
                except Exception as e:
                    st.error(str(e))

        if st.session_state.community_notes:
            for i, n in enumerate(st.session_state.community_notes):
                zc1, zc2 = st.columns([5, 1])
                with zc1:
                    routing_tag = " (affects routing)" if NOTE_CATEGORIES[n["category"]]["affects_routing"] else ""
                    st.write(f"{n['category']} **{n['name']}** -- {n['radius_m']}m radius{routing_tag}")
                with zc2:
                    if st.button("Remove", key=f"note_remove_{i}"):
                        st.session_state.community_notes.pop(i)
                        # Keep hazard_zones (routing) in sync -- rebuild it
                        # from remaining hazard-category notes.
                        st.session_state.hazard_zones = [
                            n2 for n2 in st.session_state.community_notes
                            if NOTE_CATEGORIES[n2["category"]]["affects_routing"]
                        ]
                        st.rerun()
        else:
            st.caption("No community notes added yet.")

    if not ORS_KEY:
        st.warning(ORS_KEY_MISSING_MSG)

    if st.button("Find greenest route", type="primary", key="t1_run") and ORS_KEY:
        try:
            vias = [line.strip() for line in waypoints_text.strip().splitlines() if line.strip()]
            all_stops = [origin1] + vias + [destination1]

            with st.spinner("Fetching routes..."):
                routes = fetch_routes(
                    all_stops, profile=profile, avoid_features=avoid_features,
                    hazard_zones=st.session_state.hazard_zones, ors_key=ORS_KEY,
                )

            for r in routes:
                distance_km = r.distance_m / 1000.0
                base = distance_km * base_g_per_km
                elev = r.elevation_gain_m * elevation_g_per_m
                stops = r.stop_count * stop_g_per_stop
                r.co2_grams = base + elev + stops

            routes_sorted = sorted(routes, key=lambda r: r.co2_grams)
            greenest = routes_sorted[0]

            render_international_badge(greenest)
            st.success(f"Greenest: **{greenest.summary}** (~{greenest.co2_grams/1000:.2f} kg CO2 estimated)")
            render_turn_by_turn_directions(greenest, key_prefix="t1")

            st.dataframe([{
                "Route": r.summary,
                "Distance (km)": round(r.distance_m / 1000, 2),
                "Duration (min)": round(r.duration_s / 60, 1),
                "Elevation gain (m)": round(r.elevation_gain_m, 1),
                "Stop-like turns": r.stop_count,
                "Est. CO2 (kg)": round(r.co2_grams / 1000, 3),
            } for r in routes_sorted], use_container_width=True, hide_index=True)

            layers = []
            colors = [[0, 160, 0, 200], [255, 140, 0, 160], [200, 30, 30, 160]]
            for i, r in enumerate(routes_sorted):
                color = colors[i] if i < len(colors) else [100, 100, 100, 150]
                path = [[lng, lat] for lat, lng in r.polyline_points]
                layers.append(pdk.Layer("PathLayer", data=[{"path": path}], get_path="path",
                                         get_color=color, width_scale=1, width_min_pixels=4))

            for n in st.session_state.community_notes:
                ring = circle_polygon(n["lat"], n["lng"], n["radius_m"])
                fill = NOTE_CATEGORIES[n["category"]]["color"]
                line = fill[:3] + [220]
                layers.append(pdk.Layer(
                    "PolygonLayer", data=[{"polygon": ring}], get_polygon="polygon",
                    get_fill_color=fill[:3] + [80], get_line_color=line,
                    line_width_min_pixels=2,
                ))

            mid = greenest.polyline_points[len(greenest.polyline_points) // 2]
            st.pydeck_chart(pdk.Deck(map_style="road",
                                      initial_view_state=pdk.ViewState(latitude=mid[0], longitude=mid[1], zoom=10),
                                      layers=layers))
            st.caption(
                "Green = greenest route. Red = hazard/closure (avoided). "
                "Yellow = lighting, blue = accessibility, teal = local tips (informational only)."
            )
            if greenest.elevation_profile:
                st.line_chart(greenest.elevation_profile)

            # --- Weather-safe reroute (fastest vs weather-safe trade-off) ---
            st.subheader("🌦️ Fastest vs. Weather-Safe Route")
            weather_mid = fetch_weather(mid[0], mid[1])
            if weather_mid:
                st.caption(
                    f"Currently **{weather_mid['description']}**, {weather_mid['temp_c']:.0f}°C, "
                    f"wind {weather_mid['wind_kmh']:.0f} km/h near the route midpoint."
                )

            with st.spinner("Sampling weather along the route..."):
                weather_hazards = sample_weather_hazards_along_route(greenest.polyline_points)

            weather_safe_route = None
            if weather_hazards:
                try:
                    combined_hazards = list(st.session_state.hazard_zones) + weather_hazards
                    with st.spinner("Computing weather-safe alternative..."):
                        alt_routes = fetch_routes(
                            all_stops, profile=profile, avoid_features=avoid_features,
                            hazard_zones=combined_hazards, ors_key=ORS_KEY,
                        )
                    # Prefer the fastest of the alternatives that actually
                    # differs from the baseline; fall back to the baseline
                    # itself if ORS couldn't find a distinct detour.
                    distinct = [r for r in alt_routes if r.encoded_polyline != greenest.encoded_polyline]
                    weather_safe_route = min(distinct, key=lambda r: r.duration_s) if distinct else alt_routes[0]
                except Exception:
                    weather_safe_route = None  # fall through to explanation-only messaging below

            explanation = explain_weather_reroute(greenest, weather_safe_route, weather_hazards)
            if weather_hazards and weather_safe_route and weather_safe_route.encoded_polyline != greenest.encoded_polyline:
                st.warning(explanation)
            elif weather_hazards:
                st.warning(explanation)
            else:
                st.success(explanation)

            if weather_hazards:
                hz1, hz2 = st.columns(2)
                hz1.metric("⚡ Fastest route", f"{greenest.distance_m/1000:.1f} km", f"{greenest.duration_s/60:.0f} min")
                if weather_safe_route:
                    delta_km = (weather_safe_route.distance_m - greenest.distance_m) / 1000
                    delta_min = (weather_safe_route.duration_s - greenest.duration_s) / 60
                    hz2.metric("🛡️ Weather-safe route", f"{weather_safe_route.distance_m/1000:.1f} km",
                               f"+{delta_min:.0f} min" if delta_min > 0 else f"{delta_min:.0f} min")

                # Plot both so the trade-off is visible, not just stated.
                weather_layers = [pdk.Layer(
                    "PathLayer", data=[{"path": [[lng, lat] for lat, lng in greenest.polyline_points]}],
                    get_path="path", get_color=[0, 160, 0, 200], width_min_pixels=4,
                )]
                if weather_safe_route:
                    weather_layers.append(pdk.Layer(
                        "PathLayer", data=[{"path": [[lng, lat] for lat, lng in weather_safe_route.polyline_points]}],
                        get_path="path", get_color=[30, 100, 220, 200], width_min_pixels=4,
                    ))
                weather_layers.append(pdk.Layer(
                    "ScatterplotLayer",
                    data=[{"lat": h["lat"], "lng": h["lng"]} for h in weather_hazards],
                    get_position=["lng", "lat"], get_radius=_HAZARD_ZONE_RADIUS_M,
                    get_fill_color=[220, 30, 30, 60], get_line_color=[220, 30, 30, 200], stroked=True,
                ))
                st.pydeck_chart(pdk.Deck(map_style="road",
                                          initial_view_state=pdk.ViewState(latitude=mid[0], longitude=mid[1], zoom=10),
                                          layers=weather_layers))
                st.caption("🟢 Fastest route · 🔵 Weather-safe alternative · 🔴 Flagged weather-hazard zone(s)")

            # --- Multi-modal cost optimizer ----------------------------------
            with st.expander("💰 Compare cost & time across modes"):
                st.caption(
                    "Estimates only -- free routing APIs don't expose live rideshare/transit "
                    "fares, so these are transparent, editable assumptions, not real-time quotes."
                )
                cc1, cc2, cc3 = st.columns(3)
                with cc1:
                    drive_rate = st.number_input("Driving: cost per km", 0.0, 100.0,
                                                  COST_ASSUMPTIONS["driving-car"]["per_km"], key="t1_cost_drive")
                with cc2:
                    bike_rate = st.number_input("Cycling: cost per km", 0.0, 100.0,
                                                 COST_ASSUMPTIONS["cycling-regular"]["per_km"], key="t1_cost_bike")
                with cc3:
                    walk_rate = st.number_input("Walking: cost per km", 0.0, 100.0,
                                                 COST_ASSUMPTIONS["foot-walking"]["per_km"], key="t1_cost_walk")

                if st.button("Compare all modes for this trip", key="t1_compare_modes"):
                    live_rates = {
                        "driving-car": drive_rate,
                        "cycling-regular": bike_rate,
                        "foot-walking": walk_rate,
                    }
                    compare_rows = []
                    with st.spinner("Fetching routes for each mode..."):
                        for mode_profile, mode_cfg in COST_ASSUMPTIONS.items():
                            try:
                                mode_routes = fetch_routes(all_stops, profile=mode_profile, ors_key=ORS_KEY)
                                fastest = min(mode_routes, key=lambda r: r.duration_s)
                                cost = live_rates[mode_profile] * (fastest.distance_m / 1000.0)
                                compare_rows.append({
                                    "Mode": mode_cfg["label"],
                                    "Distance (km)": round(fastest.distance_m / 1000, 2),
                                    "Time (min)": round(fastest.duration_s / 60, 1),
                                    "Est. cost": round(cost, 2),
                                })
                            except Exception:
                                compare_rows.append({
                                    "Mode": mode_cfg["label"], "Distance (km)": "--",
                                    "Time (min)": "--", "Est. cost": "no route available",
                                })
                    st.dataframe(compare_rows, use_container_width=True, hide_index=True)

            # --- Nearby amenities: hotels / restaurants / restrooms ----------
            with st.expander("🏨🍽️🚻 Nearby hotels, restaurants & restrooms"):
                st.caption(
                    "Real venues from OpenStreetMap (free, keyless). OSM records locations, not "
                    "live prices, so most prices below are transparent, editable estimates -- "
                    "labeled '(assumed)' -- unless the venue itself carries a price/fee tag, in "
                    "which case that source-reported value is shown instead."
                )
                am_c1, am_c2, am_c3 = st.columns([2, 2, 2])
                with am_c1:
                    amenity_point_label = st.radio(
                        "Search near", ["Destination", "Origin", "Route midpoint"],
                        horizontal=True, key="t1_amenity_point",
                    )
                with am_c2:
                    amenity_categories = st.multiselect(
                        "Show", list(AMENITY_CATEGORIES.keys()),
                        default=list(AMENITY_CATEGORIES.keys()), key="t1_amenity_categories",
                    )
                with am_c3:
                    amenity_radius = st.slider("Radius (m)", 200, 5000, 1200, key="t1_amenity_radius")

                pc1, pc2, pc3 = st.columns(3)
                with pc1:
                    hotel_price = st.number_input(
                        "Assumed hotel price / night (₹)", 0.0, 50000.0,
                        DEFAULT_PRICE_ASSUMPTIONS["🏨 Hotels"], key="t1_price_hotel",
                    )
                with pc2:
                    restaurant_price = st.number_input(
                        "Assumed meal price (₹)", 0.0, 10000.0,
                        DEFAULT_PRICE_ASSUMPTIONS["🍽️ Restaurants"], key="t1_price_restaurant",
                    )
                with pc3:
                    restroom_price = st.number_input(
                        "Assumed restroom fee (₹)", 0.0, 500.0,
                        DEFAULT_PRICE_ASSUMPTIONS["🚻 Restrooms"], key="t1_price_restroom",
                    )
                live_price_defaults = {
                    "🏨 Hotels": hotel_price,
                    "🍽️ Restaurants": restaurant_price,
                    "🚻 Restrooms": restroom_price,
                }

                if st.button("Find nearby amenities", key="t1_amenity_run"):
                    if amenity_point_label == "Destination":
                        am_lat, am_lng = greenest.polyline_points[-1]
                    elif amenity_point_label == "Origin":
                        am_lat, am_lng = greenest.polyline_points[0]
                    else:
                        am_lat, am_lng = mid[0], mid[1]

                    with st.spinner("Searching OpenStreetMap..."):
                        amenities = fetch_nearby_amenities(am_lat, am_lng, amenity_radius, tuple(amenity_categories))

                    any_found = any(amenities.get(cat) for cat in amenity_categories)
                    if not any_found:
                        st.warning("No nearby venues found in OpenStreetMap for this radius/category selection -- try a larger radius.")
                    else:
                        amenity_rows = []
                        amenity_layers = []
                        for cat in amenity_categories:
                            venues = amenities.get(cat, [])
                            if not venues:
                                continue
                            for v in venues:
                                price_text, is_variable = extract_price_info(cat, v["tags"], live_price_defaults[cat])
                                dist_km = haversine_km(am_lat, am_lng, v["lat"], v["lng"])
                                amenity_rows.append({
                                    "Category": cat,
                                    "Name": v["name"],
                                    "Distance (km)": round(dist_km, 2),
                                    "Price": price_text,
                                    "Price source": "Venue-reported" if is_variable else "Assumed estimate",
                                })
                            color = AMENITY_CATEGORIES[cat]["color"]
                            amenity_layers.append(pdk.Layer(
                                "ScatterplotLayer",
                                data=[{"lat": v["lat"], "lng": v["lng"], "name": v["name"]} for v in venues],
                                get_position=["lng", "lat"], get_radius=60,
                                get_fill_color=color, pickable=True,
                            ))

                        amenity_rows.sort(key=lambda row: row["Distance (km)"])
                        st.dataframe(amenity_rows, use_container_width=True, hide_index=True)

                        st.pydeck_chart(pdk.Deck(
                            map_style="road",
                            initial_view_state=pdk.ViewState(latitude=am_lat, longitude=am_lng, zoom=14),
                            layers=amenity_layers,
                            tooltip={"text": "{name}"},
                        ))
                        legend_bits = []
                        if "🏨 Hotels" in amenity_categories:
                            legend_bits.append("🟣 Hotels")
                        if "🍽️ Restaurants" in amenity_categories:
                            legend_bits.append("🟠 Restaurants")
                        if "🚻 Restrooms" in amenity_categories:
                            legend_bits.append("🔵 Restrooms")
                        st.caption(" · ".join(legend_bits) + " -- prices are per the note above, not live rates.")
        except Exception as e:
            st.error(str(e))

# ============================================================
# TAB 2 -- Ghost Jam Predictor
# ============================================================
with tab2:
    st.info(TAB_GAP_STATEMENTS["👻 Ghost Jam Predictor"])
    st.caption(
        "Simulated risk model overlaid on a real route -- illustrates phantom-jam "
        "slowdowns caused by braking behavior, not a live traffic feed."
    )
    c1, c2 = st.columns(2)
    with c1:
        origin2 = st.text_input("Origin", value="Bhubaneswar, India", key="t2_origin", help="Tip: include a 6-digit PIN code (e.g. 'Balaji Greens, Sambalpur, 768004') for hyperlocal names -- the app cross-checks against the PIN code's area to catch wrong-match geocodes.")
    with c2:
        destination2 = st.text_input("Destination", value="Puri, India", key="t2_dest", help="Tip: include a 6-digit PIN code (e.g. 'Balaji Greens, Sambalpur, 768004') for hyperlocal names -- the app cross-checks against the PIN code's area to catch wrong-match geocodes.")

    hour = st.slider("Hour of day (rush-hour weighting)", 0, 23, 9, key="t2_hour")

    if not ORS_KEY:
        st.warning(ORS_KEY_MISSING_MSG)

    if st.button("Predict ghost jams", type="primary", key="t2_run") and ORS_KEY:
        try:
            with st.spinner("Fetching real route..."):
                routes = fetch_routes([origin2, destination2], ors_key=ORS_KEY)
            route = routes[0]
            render_international_badge(route)
            render_turn_by_turn_directions(route, key_prefix="t2")
            sampled = sample_points(route.polyline_points, max_samples=60)

            rush_factor = 0.3 + math.exp(-((hour - 8) ** 2) / 8) + math.exp(-((hour - 18) ** 2) / 8)
            random.seed(42)
            risk_points = [
                {"lat": lat, "lng": lng, "weight": random.uniform(0.2, 1.0) * rush_factor}
                for lat, lng in sampled
            ]
            st.success(f"Simulated {len(risk_points)} risk points for hour={hour}:00.")

            layer = pdk.Layer("HeatmapLayer", data=risk_points, get_position=["lng", "lat"],
                               get_weight="weight", radiusPixels=40)
            mid = sampled[len(sampled) // 2]
            st.pydeck_chart(pdk.Deck(map_style="road",
                                      initial_view_state=pdk.ViewState(latitude=mid[0], longitude=mid[1], zoom=10),
                                      layers=[layer]))

            st.subheader("Why phantom jams happen")
            n_cars = 22
            positions = sorted(random.uniform(0, 100) for _ in range(n_cars))
            speeds = [5.0] * n_cars
            history = []
            for _ in range(120):
                new_positions = []
                for i in range(n_cars):
                    gap = (positions[(i + 1) % n_cars] - positions[i]) % 100
                    target_speed = min(5.0, max(0.0, gap - 2.0))
                    speeds[i] += (target_speed - speeds[i]) * 0.3
                    new_positions.append((positions[i] + speeds[i]) % 100)
                positions = new_positions
                history.append(list(speeds))
            st.line_chart(history)
            st.caption("Each line is one simulated car's speed -- waves emerge purely from spacing/braking.")
        except Exception as e:
            st.error(str(e))

# ============================================================
# TAB 3 -- AR Local History
# ============================================================
with tab3:
    st.info(TAB_GAP_STATEMENTS["🕰️ AR Local History"])
    st.caption("Web analogy of AR: real Wikipedia entries anchored to real coordinates, not phone-camera AR.")
    place = st.text_input("Place name or address", value="Konark Sun Temple, India", key="t3_place")
    radius_m = st.slider("Search radius (meters)", 100, 3000, 800, key="t3_radius")

    if st.button("Time travel here", type="primary", key="t3_run"):
        try:
            with st.spinner("Geocoding..."):
                lat, lng, _country = geocode(place)

            with st.spinner("Searching nearby historical entries..."):
                pages = wiki_geosearch(lat, lng, radius_m)

            if not pages:
                st.warning("No nearby entries found -- try a larger radius or a different place.")
            else:
                titles = "|".join(p["title"] for p in pages)
                detail_pages = wiki_page_details(titles)

                st.pydeck_chart(pdk.Deck(
                    map_style="road",
                    initial_view_state=pdk.ViewState(latitude=lat, longitude=lng, zoom=14),
                    layers=[pdk.Layer("ScatterplotLayer",
                                       data=[{"lat": p["lat"], "lng": p["lon"]} for p in pages],
                                       get_position=["lng", "lat"], get_radius=30,
                                       get_fill_color=[200, 30, 30, 200])],
                ))

                for p in pages:
                    match = next((v for v in detail_pages.values() if v.get("title") == p["title"]), None)
                    if not match:
                        continue
                    cols = st.columns([1, 3])
                    with cols[0]:
                        thumb = match.get("thumbnail", {}).get("source")
                        if thumb:
                            st.image(thumb, width=150)
                    with cols[1]:
                        st.markdown(f"**{match.get('title')}**")
                        extract = match.get("extract", "")
                        st.write(truncate_at_word(extract, 400))
                    st.divider()
        except Exception as e:
            st.error(str(e))

# ============================================================
# TAB 4 -- Offline Emergency Navigator
# ============================================================
with tab4:
    st.info(TAB_GAP_STATEMENTS["📡 Offline Navigator"])
    st.caption("Demonstrates route compression only -- not actual Bluetooth/SMS transport.")
    c1, c2 = st.columns(2)
    with c1:
        origin4 = st.text_input("Origin", value="Bhubaneswar, India", key="t4_origin", help="Tip: include a 6-digit PIN code (e.g. 'Balaji Greens, Sambalpur, 768004') for hyperlocal names -- the app cross-checks against the PIN code's area to catch wrong-match geocodes.")
    with c2:
        destination4 = st.text_input("Destination", value="Puri, India", key="t4_dest", help="Tip: include a 6-digit PIN code (e.g. 'Balaji Greens, Sambalpur, 768004') for hyperlocal names -- the app cross-checks against the PIN code's area to catch wrong-match geocodes.")

    if not ORS_KEY:
        st.warning(ORS_KEY_MISSING_MSG)

    if st.button("Compress route", type="primary", key="t4_run") and ORS_KEY:
        try:
            with st.spinner("Fetching real route..."):
                routes = fetch_routes([origin4, destination4], ors_key=ORS_KEY)
            route = routes[0]
            render_international_badge(route)
            render_turn_by_turn_directions(route, key_prefix="t4")

            raw_size = len(json.dumps({"points": route.polyline_points}).encode("utf-8"))
            full_size = len(route.encoded_polyline.encode("utf-8"))
            reduced_points = sample_points(route.polyline_points, max_samples=25)
            reduced_encoded = polyline.encode([(lat, lng) for lat, lng in reduced_points])
            reduced_size = len(reduced_encoded.encode("utf-8"))

            st.dataframe([
                {"Format": "Raw JSON (full points)", "Size (bytes)": raw_size},
                {"Format": "Full-resolution encoded polyline", "Size (bytes)": full_size},
                {"Format": "Reduced + re-encoded polyline (25 pts)", "Size (bytes)": reduced_size},
            ], use_container_width=True, hide_index=True)

            sms_segments = math.ceil(reduced_size / 140)
            st.success(f"Fits in **{reduced_size} bytes** -- roughly {sms_segments} SMS segment(s).")
            st.code(reduced_encoded, language="text")

            decoded_back = polyline.decode(reduced_encoded)
            path = [[lng, lat] for lat, lng in decoded_back]
            mid = decoded_back[len(decoded_back) // 2]
            st.pydeck_chart(pdk.Deck(
                map_style="road",
                initial_view_state=pdk.ViewState(latitude=mid[0], longitude=mid[1], zoom=10),
                layers=[pdk.Layer("PathLayer", data=[{"path": path}], get_path="path",
                                   get_color=[0, 100, 200, 200], width_min_pixels=4)],
            ))
            st.caption(f"Reconstructed from {len(decoded_back)} points decoded locally -- no API call needed.")
        except Exception as e:
            st.error(str(e))

# ============================================================
# TAB 5 -- Sensory & Safety Router
# ============================================================
with tab5:
    st.info(TAB_GAP_STATEMENTS["🧘 Sensory & Safety Router"])
    st.caption(
        "Simulated heuristic overlay on a real route -- illustrates typical noise/crowd "
        "and night-safety patterns using route geometry as a proxy (turns, road density). "
        "Not live noise sensors or crowdsourced safety reports."
    )
    c1, c2 = st.columns(2)
    with c1:
        origin5 = st.text_input("Origin", value="Bhubaneswar, India", key="t5_origin", help="Tip: include a 6-digit PIN code (e.g. 'Balaji Greens, Sambalpur, 768004') for hyperlocal names -- the app cross-checks against the PIN code's area to catch wrong-match geocodes.")
    with c2:
        destination5 = st.text_input("Destination", value="Puri, India", key="t5_dest", help="Tip: include a 6-digit PIN code (e.g. 'Balaji Greens, Sambalpur, 768004') for hyperlocal names -- the app cross-checks against the PIN code's area to catch wrong-match geocodes.")

    mode_label5 = st.radio("Travel mode", ["Walking", "Cycling"], horizontal=True, key="t5_mode")
    profile5 = {"Walking": "foot-walking", "Cycling": "cycling-regular"}[mode_label5]
    hour5 = st.slider("Hour of day (affects night-safety score)", 0, 23, 20, key="t5_hour")

    if not ORS_KEY:
        st.warning(ORS_KEY_MISSING_MSG)

    if st.button("Score this route", type="primary", key="t5_run") and ORS_KEY:
        try:
            with st.spinner("Fetching real route..."):
                routes5 = fetch_routes([origin5, destination5], profile=profile5, ors_key=ORS_KEY)
            route5 = routes5[0]
            render_international_badge(route5)
            render_turn_by_turn_directions(route5, key_prefix="t5")
            sampled5 = sample_points(route5.polyline_points, max_samples=60)

            # Noise/sensory-load heuristic: deterministic per-point pseudo-random
            # weight (seeded, so re-running with the same route gives the same
            # map) standing in for real ambient-noise/crowd-density data, which
            # no free API exposes at this granularity.
            random.seed(7)
            noise_points = [
                {"lat": lat, "lng": lng, "weight": random.uniform(0.15, 1.0)}
                for lat, lng in sampled5
            ]
            avg_noise = sum(p["weight"] for p in noise_points) / len(noise_points)
            quiet_score = round(100 * (1 - avg_noise))

            # Night-safety heuristic: risk peaks in the small hours, based on
            # hour-of-day alone (no real lighting/foot-traffic data source is
            # free/keyless at this granularity).
            def _darkness_factor(hour: int) -> float:
                diff = min(abs(hour - 2), 24 - abs(hour - 2))
                return max(0.2, 1.0 - diff / 12)

            darkness = _darkness_factor(hour5)
            random.seed(13)
            safety_points = [
                {"lat": lat, "lng": lng, "weight": random.uniform(0.1, 0.9) * darkness}
                for lat, lng in sampled5
            ]
            avg_safety_risk = sum(p["weight"] for p in safety_points) / len(safety_points)
            safety_score = round(100 * (1 - avg_safety_risk / max(darkness, 0.01)) * (1 - darkness * 0.5))
            safety_score = max(0, min(100, safety_score))

            m1, m2 = st.columns(2)
            m1.metric("🧘 Sensory-friendliness score", f"{quiet_score}/100",
                      help="Higher = quieter, lower sensory load (simulated).")
            m2.metric("🌙 Night-safety score", f"{safety_score}/100",
                      help=f"For {hour5}:00 -- lower at night, simulated from time-of-day only.")

            tab5_view = st.radio("Show overlay", ["Sensory load", "Night safety"], horizontal=True, key="t5_view")
            layer_data = noise_points if tab5_view == "Sensory load" else safety_points
            heat_layer = pdk.Layer("HeatmapLayer", data=layer_data, get_position=["lng", "lat"],
                                    get_weight="weight", radiusPixels=40)
            mid5 = sampled5[len(sampled5) // 2]
            st.pydeck_chart(pdk.Deck(map_style="road",
                                      initial_view_state=pdk.ViewState(latitude=mid5[0], longitude=mid5[1], zoom=10),
                                      layers=[heat_layer]))
            st.caption(
                "Darker/hotter areas = higher simulated sensory load or night-safety risk, "
                "depending on the overlay selected above."
            )
        except Exception as e:
            st.error(str(e))

# ============================================================
# TAB 6 -- ADAS Collision Watch (CV + optional VLM) & Voice Route Assistant
# ============================================================
with tab6:
    st.info(TAB_GAP_STATEMENTS["🚨 ADAS Collision Watch & Voice Nav"])
    st.caption(
        "Two independent demos on one tab: a still-frame collision-risk check (CV, plus an "
        "optional VLM hazard read), and a voice-driven route assistant. Neither controls a "
        "real vehicle -- this is a software prototype, not a certified safety system."
    )

    # --- Collision Watch ------------------------------------------------
    st.subheader("🚨 Collision Watch")
    st.caption(
        "Analyzes **one still frame** (webcam snapshot or uploaded photo) at a time -- not a "
        "continuous live video feed. CV detection (YOLOv8n) runs locally and needs no API key; "
        "it flags nearby vehicles/cyclists/pedestrians by how large and centered they are in "
        "frame. The optional VLM step sends that same frame to Claude vision (needs your own "
        "Anthropic API key) for a plain-language interpretation the raw boxes can't give."
    )

    cw_source = st.radio("Frame source", ["Camera snapshot", "Upload photo"], horizontal=True, key="t6_source")
    frame = None
    if cw_source == "Camera snapshot":
        cam_file = st.camera_input("Take a forward-facing snapshot", key="t6_camera")
        if cam_file:
            frame = Image.open(cam_file)
    else:
        up_file = st.file_uploader("Upload a dashcam-style photo", type=["jpg", "jpeg", "png"], key="t6_upload")
        if up_file:
            frame = Image.open(up_file)

    anthropic_key = get_anthropic_key()
    use_vlm = st.checkbox("Also get a VLM hazard read (Claude vision)", value=bool(anthropic_key), key="t6_use_vlm")
    if use_vlm and not anthropic_key:
        st.caption(
            "No ANTHROPIC_API_KEY found -- add one to your .env file or Streamlit Secrets to "
            "enable this step (get a key at https://console.anthropic.com/settings/keys). "
            "Running CV-only for now."
        )
    vlm_model = DEFAULT_VLM_MODEL
    if use_vlm and anthropic_key:
        vlm_model = st.text_input("Claude model", value=DEFAULT_VLM_MODEL, key="t6_vlm_model")

    if frame is not None and st.button("Analyze frame", type="primary", key="t6_analyze"):
        with st.spinner("Running detector (first run downloads YOLOv8n weights, ~6MB)..."):
            annotated, detections, overall = run_collision_detection(frame)

        if annotated is None:
            st.error(
                "Collision detection isn't available -- the `ultralytics` package is either not "
                "installed or failed to load weights (needs internet on first run). Install it "
                "with `pip install ultralytics` and try again."
            )
        else:
            worst_level = max((d["risk_level"] for d in detections), default=0)
            {0: st.success, 1: st.info, 2: st.warning, 3: st.error}[worst_level](f"**{overall}**")

            st.image(annotated, use_container_width=True, caption="Bounding boxes colored by proximity risk.")

            if detections:
                st.dataframe([
                    {"Object": d["class"], "Confidence": f"{d['confidence']:.0%}", "Risk": d["risk_label"]}
                    for d in detections
                ], use_container_width=True, hide_index=True)
            else:
                st.caption("No vehicles, cyclists, or pedestrians detected in this frame.")

            if use_vlm and anthropic_key:
                try:
                    with st.spinner("Asking Claude vision for a hazard read..."):
                        vlm_text = describe_scene_with_vlm(frame, detections, anthropic_key, vlm_model)
                    st.markdown(f"🧠 **VLM hazard read:** {vlm_text}")
                except Exception as e:
                    st.error(f"VLM step failed: {e}")

    st.divider()

    # --- Voice Route Assistant -------------------------------------------
    st.subheader("🎙️ Voice Route Assistant")
    st.caption(
        "Speech recognition and text-to-speech run **in your browser** (Chrome recommended) -- "
        "no audio is ever sent to this server, only the recognized text. Try saying "
        "\"navigate to Puri\" or \"directions to Konark Sun Temple\"."
    )
    origin6 = st.text_input("Your current location (origin)", value="Bhubaneswar, India", key="t6_origin")

    if not ORS_KEY:
        st.warning(ORS_KEY_MISSING_MSG)

    components.html(
        """
        <div style="font-family: sans-serif;">
          <button id="t6startBtn" style="padding:8px 16px; font-size:16px; cursor:pointer;">
            🎤 Start Listening
          </button>
          <p id="t6output" style="margin-top:10px;">Tap the button and speak your destination.</p>
        </div>
        <script>
        (function() {
          const startBtn = document.getElementById('t6startBtn');
          const output = document.getElementById('t6output');
          const SpeechRecognition = window.SpeechRecognition || window.webkitSpeechRecognition;
          if (!SpeechRecognition) {
            output.innerText = 'Speech recognition not supported in this browser -- try Chrome.';
            startBtn.disabled = true;
            return;
          }
          const recognition = new SpeechRecognition();
          recognition.lang = 'en-IN';
          recognition.onresult = function(event) {
            const text = event.results[0][0].transcript;
            output.innerText = 'Heard: "' + text + '" -- looking up your route...';
            const url = new URL(window.top.location.href);
            url.searchParams.set('voice_query', text);
            url.searchParams.set('t', Date.now());
            window.top.location.href = url.toString();
          };
          recognition.onerror = function(event) {
            output.innerText = 'Error: ' + event.error;
          };
          startBtn.onclick = function() { recognition.start(); };
        })();
        </script>
        """,
        height=100,
    )

    if "t6_last_voice_query" not in st.session_state:
        st.session_state.t6_last_voice_query = None

    voice_query = st.query_params.get("voice_query", None)
    is_new_query = voice_query and voice_query != st.session_state.t6_last_voice_query

    if is_new_query and ORS_KEY:
        st.session_state.t6_last_voice_query = voice_query
        destination6 = parse_voice_destination(voice_query)
        st.write(f"🎤 Heard: \"{voice_query}\" -- interpreting destination as **{destination6}**")

        spoken = None
        try:
            with st.spinner(f"Finding route to {destination6}..."):
                routes6 = fetch_routes([origin6, destination6], profile="driving-car", ors_key=ORS_KEY)
            route6 = min(routes6, key=lambda r: r.duration_s)
            render_international_badge(route6)

            dist_km = route6.distance_m / 1000.0
            dur_min = route6.duration_s / 60.0
            turn_word = "turn" if route6.stop_count == 1 else "turns"
            st.success(
                f"{destination6} is {dist_km:.1f} kilometers away, about {dur_min:.0f} minutes by car, "
                f"with {route6.stop_count} {turn_word} along the way."
            )

            # This is the actual point-A-to-point-B guidance: every real turn, in
            # order, not just a total distance/duration/turn-count. Both spoken
            # (below, via browser TTS) and shown on screen use it.
            render_turn_by_turn_directions(route6, key_prefix="t6", expanded=True)
            spoken = directions_speech_text(route6, destination6)

            mid6 = route6.polyline_points[len(route6.polyline_points) // 2]
            st.pydeck_chart(pdk.Deck(
                map_style="road",
                initial_view_state=pdk.ViewState(latitude=mid6[0], longitude=mid6[1], zoom=10),
                layers=[pdk.Layer(
                    "PathLayer",
                    data=[{"path": [[lng, lat] for lat, lng in route6.polyline_points]}],
                    get_path="path", get_color=[30, 100, 220, 200], width_min_pixels=4,
                )],
            ))
        except Exception as e:
            st.error(str(e))
            spoken = f"Sorry, I could not find a route to {destination6}."

        # Speak the result back -- browser-side text-to-speech, no server audio involved.
        components.html(
            f"""
            <script>
            (function() {{
              const utter = new SpeechSynthesisUtterance({json.dumps(spoken)});
              utter.lang = 'en-IN';
              window.speechSynthesis.cancel();
              window.speechSynthesis.speak(utter);
            }})();
            </script>
            """,
            height=0,
        )
    elif voice_query and not ORS_KEY:
        st.warning(ORS_KEY_MISSING_MSG)