# -*- coding: utf-8 -*-
"""APP.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ysyxe-efvKwoto7zQAMT7ozkWe9DnZFH
"""

import os
import json
import math
import random
from dataclasses import dataclass, field
from typing import List, Optional

import requests
import polyline
import pydeck as pdk
import streamlit as st
from dotenv import load_dotenv

load_dotenv()

ORS_DIRECTIONS_URL_TMPL = "https://api.openrouteservice.org/v2/directions/{profile}/geojson"
NOMINATIM_URL = "https://nominatim.openstreetmap.org/search"
WIKI_API = "https://en.wikipedia.org/w/api.php"

REQUEST_HEADERS = {"User-Agent": "MapQuestSuite/1.0 (educational demo project)"}

PROFILES = {
    "Driving": "driving-car",
    "Cycling": "cycling-regular",
    "Walking": "foot-walking",
}

AVOID_OPTIONS_BY_PROFILE = {
    "driving-car": {"Highways": "highways", "Tolls": "tollways", "Ferries": "ferries"},
    "cycling-regular": {"Ferries": "ferries", "Steps": "steps"},
    "foot-walking": {"Ferries": "ferries", "Steps": "steps"},
}


STOP_LIKE_MANEUVER_TYPES = {0, 1, 2, 3, 4, 5, 7, 8, 9, 12, 13}


def get_ors_key() -> str:
    try:
        if "ORS_API_KEY" in st.secrets:
            return st.secrets["ORS_API_KEY"]
    except Exception:
        pass
    return os.getenv("ORS_API_KEY", "")


def safe_json(resp: requests.Response, source: str) -> dict:
    try:
        return resp.json()
    except Exception:
        snippet = resp.text[:200].replace("\n", " ") if resp.text else "(empty body)"
        raise RuntimeError(f"{source} returned a non-JSON response (HTTP {resp.status_code}): {snippet}")





class RouteResult:
    summary: str
    distance_m: float
    duration_s: float
    duration_in_traffic_s: Optional[float]
    stop_count: int
    polyline_points: List[List[float]]
    encoded_polyline: str
    elevation_profile: List[float] = field(default_factory=list)
    elevation_gain_m: float = 0.0
    co2_grams: float = 0.0


def geocode(place: str) -> tuple:
    resp = requests.get(
        NOMINATIM_URL, params={"q": place, "format": "json", "limit": 1},
        headers=REQUEST_HEADERS, timeout=15,
    )
    results = safe_json(resp, "Nominatim geocoding")
    if not results:
        raise RuntimeError(f"Could not geocode '{place}' -- try a more specific place name.")
    return float(results[0]["lat"]), float(results[0]["lon"])


def compute_elevation_gain(profile: List[float]) -> float:
    gain = 0.0
    for prev, curr in zip(profile, profile[1:]):
        if curr - prev > 0:
            gain += curr - prev
    return gain


def circle_polygon(lat: float, lng: float, radius_m: float, n_points: int = 16) -> List[List[float]]:
    """Approximate a circle as a closed polygon ring [[lng, lat], ...] for avoid_polygons."""
    R = 6371000.0
    lat_rad = math.radians(lat)
    ring = []
    for i in range(n_points):
        angle = 2 * math.pi * i / n_points
        dlat = (radius_m * math.cos(angle)) / R
        dlng = (radius_m * math.sin(angle)) / (R * math.cos(lat_rad))
        ring.append([lng + math.degrees(dlng), lat + math.degrees(dlat)])
    ring.append(ring[0])
    return ring


def build_avoid_polygons(hazard_zones: List[dict]) -> Optional[dict]:
    if not hazard_zones:
        return None
    polygons = [[circle_polygon(z["lat"], z["lng"], z["radius_m"])] for z in hazard_zones]
    return {"type": "MultiPolygon", "coordinates": polygons}


def _fetch_single_route(
    coords_lnglat: List[List[float]], profile: str, preference: str,
    avoid_features: List[str], avoid_polygons: Optional[dict], ors_key: str,
) -> Optional[dict]:
    body = {
        "coordinates": coords_lnglat,
        "elevation": True,
        "instructions": True,
        "preference": preference,
    }
    options = {}
    if avoid_features:
        options["avoid_features"] = avoid_features
    if avoid_polygons:
        options["avoid_polygons"] = avoid_polygons
    if options:
        body["options"] = options

    url = ORS_DIRECTIONS_URL_TMPL.format(profile=profile)
    headers = {"Authorization": ors_key, "Content-Type": "application/json"}
    resp = requests.post(url, json=body, headers=headers, timeout=20)
    data = safe_json(resp, "OpenRouteService")
    if resp.status_code != 200:
        msg = data.get("error", {}).get("message", str(data))
        raise RuntimeError(f"OpenRouteService error: {msg}")
    features = data.get("features", [])
    return features[0] if features else None


def fetch_routes(
    waypoint_addresses: List[str], profile: str = "driving-car",
    avoid_features: Optional[List[str]] = None,
    hazard_zones: Optional[List[dict]] = None,
    ors_key: str = "",
) -> List[RouteResult]:
    avoid_features = avoid_features or []
    avoid_polygons = build_avoid_polygons(hazard_zones or [])

    coords_lnglat = []
    for addr in waypoint_addresses:
        lat, lng = geocode(addr)
        coords_lnglat.append([lng, lat])

    preferences = [("recommended", "Recommended route"), ("shortest", "Shortest route")]
    results = []
    seen_distances = set()
    for preference, label in preferences:
        feature = _fetch_single_route(coords_lnglat, profile, preference, avoid_features, avoid_polygons, ors_key)
        if feature is None:
            continue
        props = feature["properties"]
        summary = props.get("summary", {})
        distance_m = summary.get("distance", 0.0)

        rounded = round(distance_m, -2)
        if rounded in seen_distances:
            continue
        seen_distances.add(rounded)

        duration_s = summary.get("duration", 0.0)
        stop_count = 0
        for segment in props.get("segments", []):
            for step in segment.get("steps", []):
                if step.get("type") in STOP_LIKE_MANEUVER_TYPES:
                    stop_count += 1

        coords = feature["geometry"]["coordinates"]
        points = [[c[1], c[0]] for c in coords]
        elevation_profile = [c[2] for c in coords if len(c) > 2]
        encoded = polyline.encode([(lat, lng) for lat, lng in points])

        r = RouteResult(
            summary=label, distance_m=distance_m, duration_s=duration_s,
            duration_in_traffic_s=None, stop_count=stop_count,
            polyline_points=points, encoded_polyline=encoded,
            elevation_profile=elevation_profile,
        )
        r.elevation_gain_m = compute_elevation_gain(elevation_profile)
        results.append(r)

    if not results:
        raise RuntimeError("No routes returned -- try different locations or fewer restrictions.")
    return results


def sample_points(points: List[List[float]], max_samples: int = 100) -> List[List[float]]:
    if len(points) <= max_samples:
        return points
    step = len(points) / max_samples
    return [points[int(i * step)] for i in range(max_samples)]




st.set_page_config(page_title="MapQuest Suite", layout="wide")
st.title(" MapQuest Suite")
st.caption("Four Google Maps concepts in one app -- built on free, no-credit-card APIs.")

ORS_KEY = get_ors_key()
if not ORS_KEY:
    st.error(
        "No ORS_API_KEY found. Get a free key (no card needed) at "
        "https://openrouteservice.org/dev/#/signup -- then locally put it in a .env file, "
        "or on Streamlit Community Cloud add it under Settings > Secrets as:\n"
        'ORS_API_KEY = "your_real_key_here"'
    )
    st.stop()

if "hazard_zones" not in st.session_state:
    st.session_state.hazard_zones = []

tab1, tab2, tab3, tab4 = st.tabs([
    " Greenest Route",
    " Ghost Jam Predictor",
    " AR Local History",
    " Offline Navigator",
])


with tab1:
    c1, c2 = st.columns(2)
    with c1:
        origin1 = st.text_input("Origin", value="Bhubaneswar, India", key="t1_origin")
    with c2:
        destination1 = st.text_input("Destination", value="Puri, India", key="t1_dest")

    with st.expander(" Routing options"):
        mode_label = st.radio("Travel mode", list(PROFILES.keys()), horizontal=True, key="t1_mode")
        profile = PROFILES[mode_label]

        avoid_map = AVOID_OPTIONS_BY_PROFILE[profile]
        avoid_labels = st.multiselect("Avoid", list(avoid_map.keys()), key="t1_avoid")
        avoid_features = [avoid_map[label] for label in avoid_labels]

        waypoints_text = st.text_area(
            "Extra stops (optional, one per line, visited in order)",
            placeholder="e.g.\nChandaka Wildlife Sanctuary\nPipili",
            key="t1_waypoints",
        )

        st.caption("CO2 model weights (assumptions, not official emission factors)")
        wc1, wc2, wc3 = st.columns(3)
        with wc1:
            base_g_per_km = st.slider("g CO2 / km", 80, 250, 120, key="t1_base")
        with wc2:
            elevation_g_per_m = st.slider("g CO2 / m climbed", 0.0, 5.0, 1.5, key="t1_elev")
        with wc3:
            stop_g_per_stop = st.slider("g CO2 / stop", 0, 50, 15, key="t1_stop")

    with st.expander(" Hazard zones (routes will avoid these)"):
        st.caption("Mark real hazards (flooding, closures, accidents) and routes will route around them.")
        hc1, hc2, hc3 = st.columns([3, 1, 1])
        with hc1:
            hz_place = st.text_input("Place name", key="hz_place", label_visibility="collapsed", placeholder="Place name")
        with hc2:
            hz_radius = st.number_input("Radius (m)", 50, 20000, 500, key="hz_radius", label_visibility="collapsed")
        with hc3:
            if st.button("Add zone", key="hz_add"):
                try:
                    lat, lng = geocode(hz_place)
                    st.session_state.hazard_zones.append(
                        {"name": hz_place, "lat": lat, "lng": lng, "radius_m": hz_radius}
                    )
                except Exception as e:
                    st.error(str(e))

        if st.session_state.hazard_zones:
            for i, z in enumerate(st.session_state.hazard_zones):
                zc1, zc2 = st.columns([5, 1])
                with zc1:
                    st.write(f"🚧 {z['name']} -- {z['radius_m']}m radius")
                with zc2:
                    if st.button("Remove", key=f"hz_remove_{i}"):
                        st.session_state.hazard_zones.pop(i)
                        st.rerun()
        else:
            st.caption("No hazard zones added yet.")

    if st.button("Find greenest route", type="primary", key="t1_run"):
        try:
            vias = [line.strip() for line in waypoints_text.strip().splitlines() if line.strip()]
            all_stops = [origin1] + vias + [destination1]

            with st.spinner("Fetching routes..."):
                routes = fetch_routes(
                    all_stops, profile=profile, avoid_features=avoid_features,
                    hazard_zones=st.session_state.hazard_zones, ors_key=ORS_KEY,
                )

            for r in routes:
                distance_km = r.distance_m / 1000.0
                base = distance_km * base_g_per_km
                elev = r.elevation_gain_m * elevation_g_per_m
                stops = r.stop_count * stop_g_per_stop
                r.co2_grams = base + elev + stops

            routes_sorted = sorted(routes, key=lambda r: r.co2_grams)
            greenest = routes_sorted[0]
            st.success(f"Greenest: **{greenest.summary}** (~{greenest.co2_grams/1000:.2f} kg CO2 estimated)")

            st.dataframe([{
                "Route": r.summary,
                "Distance (km)": round(r.distance_m / 1000, 2),
                "Duration (min)": round(r.duration_s / 60, 1),
                "Elevation gain (m)": round(r.elevation_gain_m, 1),
                "Stop-like turns": r.stop_count,
                "Est. CO2 (kg)": round(r.co2_grams / 1000, 3),
            } for r in routes_sorted], use_container_width=True, hide_index=True)

            layers = []
            colors = [[0, 160, 0, 200], [255, 140, 0, 160], [200, 30, 30, 160]]
            for i, r in enumerate(routes_sorted):
                color = colors[i] if i < len(colors) else [100, 100, 100, 150]
                path = [[lng, lat] for lat, lng in r.polyline_points]
                layers.append(pdk.Layer("PathLayer", data=[{"path": path}], get_path="path",
                                         get_color=color, width_scale=1, width_min_pixels=4))

            for z in st.session_state.hazard_zones:
                ring = circle_polygon(z["lat"], z["lng"], z["radius_m"])
                layers.append(pdk.Layer(
                    "PolygonLayer", data=[{"polygon": ring}], get_polygon="polygon",
                    get_fill_color=[220, 30, 30, 80], get_line_color=[220, 30, 30, 200],
                    line_width_min_pixels=2,
                ))

            mid = greenest.polyline_points[len(greenest.polyline_points) // 2]
            st.pydeck_chart(pdk.Deck(map_style="road",
                                      initial_view_state=pdk.ViewState(latitude=mid[0], longitude=mid[1], zoom=10),
                                      layers=layers))
            st.caption("Green = greenest route. Red shaded circles = hazard zones being avoided.")
            if greenest.elevation_profile:
                st.line_chart(greenest.elevation_profile)
        except Exception as e:
            st.error(str(e))


with tab2:
    st.info(
        "Simulated risk model overlaid on a real route -- illustrates phantom-jam "
        "slowdowns caused by braking behavior, not a live traffic feed."
    )
    c1, c2 = st.columns(2)
    with c1:
        origin2 = st.text_input("Origin", value="Bhubaneswar, India", key="t2_origin")
    with c2:
        destination2 = st.text_input("Destination", value="Puri, India", key="t2_dest")

    hour = st.slider("Hour of day (rush-hour weighting)", 0, 23, 9, key="t2_hour")

    if st.button("Predict ghost jams", type="primary", key="t2_run"):
        try:
            with st.spinner("Fetching real route..."):
                routes = fetch_routes([origin2, destination2], ors_key=ORS_KEY)
            route = routes[0]
            sampled = sample_points(route.polyline_points, max_samples=60)

            rush_factor = 0.3 + math.exp(-((hour - 8) ** 2) / 8) + math.exp(-((hour - 18) ** 2) / 8)
            random.seed(42)
            risk_points = [
                {"lat": lat, "lng": lng, "weight": random.uniform(0.2, 1.0) * rush_factor}
                for lat, lng in sampled
            ]
            st.success(f"Simulated {len(risk_points)} risk points for hour={hour}:00.")

            layer = pdk.Layer("HeatmapLayer", data=risk_points, get_position=["lng", "lat"],
                               get_weight="weight", radiusPixels=40)
            mid = sampled[len(sampled) // 2]
            st.pydeck_chart(pdk.Deck(map_style="road",
                                      initial_view_state=pdk.ViewState(latitude=mid[0], longitude=mid[1], zoom=10),
                                      layers=[layer]))

            st.subheader("Why phantom jams happen")
            n_cars = 22
            positions = sorted(random.uniform(0, 100) for _ in range(n_cars))
            speeds = [5.0] * n_cars
            history = []
            for _ in range(120):
                new_positions = []
                for i in range(n_cars):
                    gap = (positions[(i + 1) % n_cars] - positions[i]) % 100
                    target_speed = min(5.0, max(0.0, gap - 2.0))
                    speeds[i] += (target_speed - speeds[i]) * 0.3
                    new_positions.append((positions[i] + speeds[i]) % 100)
                positions = new_positions
                history.append(list(speeds))
            st.line_chart(history)
            st.caption("Each line is one simulated car's speed -- waves emerge purely from spacing/braking.")
        except Exception as e:
            st.error(str(e))


with tab3:
    st.info("Web analogy of AR: real Wikipedia entries anchored to real coordinates, not phone-camera AR.")
    place = st.text_input("Place name or address", value="Konark Sun Temple, India", key="t3_place")
    radius_m = st.slider("Search radius (meters)", 100, 3000, 800, key="t3_radius")

    if st.button("Time travel here", type="primary", key="t3_run"):
        try:
            with st.spinner("Geocoding..."):
                lat, lng = geocode(place)

            with st.spinner("Searching nearby historical entries..."):
                geo_raw = requests.get(WIKI_API, params={
                    "action": "query", "list": "geosearch", "gscoord": f"{lat}|{lng}",
                    "gsradius": radius_m, "gslimit": 6, "format": "json",
                }, headers=REQUEST_HEADERS, timeout=15)
                geo_resp = safe_json(geo_raw, "Wikipedia geosearch")
                pages = geo_resp.get("query", {}).get("geosearch", [])

            if not pages:
                st.warning("No nearby entries found -- try a larger radius or a different place.")
            else:
                titles = "|".join(p["title"] for p in pages)
                detail_raw = requests.get(WIKI_API, params={
                    "action": "query", "prop": "extracts|pageimages", "exintro": True,
                    "explaintext": True, "piprop": "thumbnail", "pithumbsize": 400,
                    "titles": titles, "format": "json",
                }, headers=REQUEST_HEADERS, timeout=15)
                detail_resp = safe_json(detail_raw, "Wikipedia page details")
                detail_pages = detail_resp.get("query", {}).get("pages", {})

                st.pydeck_chart(pdk.Deck(
                    map_style="road",
                    initial_view_state=pdk.ViewState(latitude=lat, longitude=lng, zoom=14),
                    layers=[pdk.Layer("ScatterplotLayer",
                                       data=[{"lat": p["lat"], "lng": p["lon"]} for p in pages],
                                       get_position=["lng", "lat"], get_radius=30,
                                       get_fill_color=[200, 30, 30, 200])],
                ))

                for p in pages:
                    match = next((v for v in detail_pages.values() if v.get("title") == p["title"]), None)
                    if not match:
                        continue
                    cols = st.columns([1, 3])
                    with cols[0]:
                        thumb = match.get("thumbnail", {}).get("source")
                        if thumb:
                            st.image(thumb, width=150)
                    with cols[1]:
                        st.markdown(f"**{match.get('title')}**")
                        extract = match.get("extract", "")
                        st.write(extract[:400] + ("..." if len(extract) > 400 else ""))
                    st.divider()
        except Exception as e:
            st.error(str(e))

with tab4:
    st.info("Demonstrates route compression only -- not actual Bluetooth/SMS transport.")
    c1, c2 = st.columns(2)
    with c1:
        origin4 = st.text_input("Origin", value="Bhubaneswar, India", key="t4_origin")
    with c2:
        destination4 = st.text_input("Destination", value="Puri, India", key="t4_dest")

    if st.button("Compress route", type="primary", key="t4_run"):
        try:
            with st.spinner("Fetching real route..."):
                routes = fetch_routes([origin4, destination4], ors_key=ORS_KEY)
            route = routes[0]

            raw_size = len(json.dumps({"points": route.polyline_points}).encode("utf-8"))
            full_size = len(route.encoded_polyline.encode("utf-8"))
            reduced_points = sample_points(route.polyline_points, max_samples=25)
            reduced_encoded = polyline.encode([(lat, lng) for lat, lng in reduced_points])
            reduced_size = len(reduced_encoded.encode("utf-8"))

            st.dataframe([
                {"Format": "Raw JSON (full points)", "Size (bytes)": raw_size},
                {"Format": "Full-resolution encoded polyline", "Size (bytes)": full_size},
                {"Format": "Reduced + re-encoded polyline (25 pts)", "Size (bytes)": reduced_size},
            ], use_container_width=True, hide_index=True)

            sms_segments = math.ceil(reduced_size / 140)
            st.success(f"Fits in **{reduced_size} bytes** -- roughly {sms_segments} SMS segment(s).")
            st.code(reduced_encoded, language="text")

            decoded_back = polyline.decode(reduced_encoded)
            path = [[lng, lat] for lat, lng in decoded_back]
            mid = decoded_back[len(decoded_back) // 2]
            st.pydeck_chart(pdk.Deck(
                map_style="road",
                initial_view_state=pdk.ViewState(latitude=mid[0], longitude=mid[1], zoom=10),
                layers=[pdk.Layer("PathLayer", data=[{"path": path}], get_path="path",
                                   get_color=[0, 100, 200, 200], width_min_pixels=4)],
            ))
            st.caption(f"Reconstructed from {len(decoded_back)} points decoded locally -- no API call needed.")
        except Exception as e:
            st.error(str(e))