# -*- coding: utf-8 -*-
"""APP.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ysyxe-efvKwoto7zQAMT7ozkWe9DnZFH
"""

import difflib
import html as _html_module


JSONLD_FETCH_TIMEOUT_S = 12

_JSONLD_SCRIPT_RE = re.compile(
    r'<script[^>]+type=["\']application/ld\+json["\'][^>]*>(.*?)</script>',
    re.IGNORECASE | re.DOTALL,
)


def _find_local_business_node(parsed) -> Optional[dict]:
    """JSON-LD can be a single object, a list, or wrapped in @graph -- dig
    through all three shapes looking for a LocalBusiness-ish node (any
    @type containing 'Business', 'Restaurant', 'Store', etc., since
    schema.org has dozens of specific subtypes)."""
    candidates = []
    if isinstance(parsed, list):
        candidates = parsed
    elif isinstance(parsed, dict):
        if "@graph" in parsed and isinstance(parsed["@graph"], list):
            candidates = parsed["@graph"]
        else:
            candidates = [parsed]

    for node in candidates:
        if not isinstance(node, dict):
            continue
        node_type = node.get("@type", "")
        type_str = " ".join(node_type) if isinstance(node_type, list) else str(node_type)
        if any(kw in type_str for kw in ("Business", "Restaurant", "Store", "Organization", "Cafe", "Hotel")):
            return node
    return None


def fetch_website_listing(url: str) -> Optional[dict]:
    """Fetches a business's own website and extracts schema.org JSON-LD
    structured data (name, phone, address, opening hours) -- this is Source
    A: the business's own stated info, no API key or billing needed, works
    for businesses anywhere in the world (India included) as long as the
    site has SEO structured data, which most modern business sites do."""
    try:
        resp = _session.get(url, headers=REQUEST_HEADERS, timeout=JSONLD_FETCH_TIMEOUT_S)
    except Exception as e:
        raise RuntimeError(f"Couldn't reach {url}: {e}")

    if resp.status_code != 200:
        raise RuntimeError(f"{url} returned HTTP {resp.status_code}")

    matches = _JSONLD_SCRIPT_RE.findall(resp.text)
    for raw in matches:
        try:
            parsed = json.loads(_html_module.unescape(raw.strip()))
        except Exception:
            continue
        node = _find_local_business_node(parsed)
        if node:
            addr = node.get("address")
            if isinstance(addr, dict):
                addr_str = ", ".join(filter(None, [
                    addr.get("streetAddress"), addr.get("addressLocality"),
                    addr.get("addressRegion"), addr.get("postalCode"),
                ]))
            else:
                addr_str = addr if isinstance(addr, str) else None

            hours = node.get("openingHours") or node.get("openingHoursSpecification")
            if isinstance(hours, list):
                hours = "; ".join(str(h) for h in hours)

            return {
                "name": node.get("name"),
                "phone": node.get("telephone"),
                "address": addr_str,
                "opening_hours": hours,
            }
    return None


def fetch_osm_listing(business_name: str, lat: float, lng: float, radius_m: int = 300) -> Optional[dict]:
    """Looks up the same business in OpenStreetMap (via Overpass), as a
    second, independent, free/keyless source -- this app's 'ground truth
    check' alongside Yelp."""
    overpass_ql = (
        f'[out:json][timeout:20];'
        f'node["name"~"{business_name}",i](around:{radius_m},{lat},{lng});'
        f"out center 5;"
    )
    try:
        resp = _session.post(OVERPASS_URL, data={"data": overpass_ql},
                              headers=REQUEST_HEADERS, timeout=25)
        data = safe_json(resp, "Overpass")
    except Exception:
        return None

    elements = data.get("elements", [])
    if not elements:
        return None
    tags = elements[0].get("tags", {})
    return {
        "name": tags.get("name"),
        "phone": tags.get("phone") or tags.get("contact:phone"),
        "opening_hours": tags.get("opening_hours"),
        "address": ", ".join(filter(None, [
            tags.get("addr:housenumber"), tags.get("addr:street"), tags.get("addr:city"),
        ])) or None,
    }


def _fuzzy_match(a: Optional[str], b: Optional[str]) -> float:
    """0..1 similarity between two strings, tolerant of formatting
    differences (e.g. phone number punctuation, minor address wording)."""
    if not a or not b:
        return 0.0
    return difflib.SequenceMatcher(None, a.lower().strip(), b.lower().strip()).ratio()


_DIGITS_RE = re.compile(r"\d+")


def _phones_match(a: Optional[str], b: Optional[str]) -> bool:
    """Phone comparison by digits only, handling three common formatting
    differences that generic string similarity gets wrong:
      1. Punctuation/spacing (+91-674-1234567 vs 91 674 1234567)
      2. Country code present vs. absent (91674... vs 674...)
      3. India's domestic trunk prefix '0' vs. country code '91'
         (0674-1234567 vs +91-674-1234567 -- the SAME number, but a
         leading 0 replaces where +91 would go, which plain digit
         suffix-matching doesn't handle)."""
    if not a or not b:
        return False
    da, db = "".join(_DIGITS_RE.findall(a)), "".join(_DIGITS_RE.findall(b))
    if not da or not db:
        return False
    # Strip a leading domestic trunk '0' (India-style) before comparing,
    # so '0674...' and '91674...' both normalize to '674...'.
    da_norm = da[1:] if da.startswith("0") else da
    db_norm = db[1:] if db.startswith("0") else db
    shorter, longer = (da_norm, db_norm) if len(da_norm) <= len(db_norm) else (db_norm, da_norm)
    return longer.endswith(shorter) and len(shorter) >= 7


_HOURS_TIME_RE = re.compile(r"(\d{1,2}):(\d{2})")


def _hours_match(a: Optional[str], b: Optional[str]) -> bool:
    """Hours comparison by extracted HH:MM tokens, not raw string
    similarity -- generic fuzzy matching scores 'Mo-Sa 09:00-21:00' as
    near-identical to 'Mo-Sa 10:00-20:00' because they share most
    characters, which would silently hide a real mismatch. This instead
    requires the actual time tokens to match."""
    if not a or not b:
        return False
    times_a = _HOURS_TIME_RE.findall(a)
    times_b = _HOURS_TIME_RE.findall(b)
    if not times_a or not times_b:
        return _fuzzy_match(a, b) >= 0.8  # no parseable times -- fall back, but stricter
    return set(times_a) == set(times_b)


def compare_listings(website: Optional[dict], osm: Optional[dict]) -> dict:
    """Field-by-field comparison producing a status + confidence per field,
    plus an overall trust score. Source A is the business's own website
    (JSON-LD), Source B is OpenStreetMap -- source-agnostic in structure,
    so swapping in Google Places or Yelp later needs no change here, as
    long as the caller passes the same {name, phone, address,
    opening_hours} shape."""
    fields = {}

    def _field_fuzzy(label, a, b, threshold=0.6):
        if not a and not b:
            return {"label": label, "status": "no_data", "website": a, "osm": b}
        if not a or not b:
            return {"label": label, "status": "unverifiable", "website": a, "osm": b}
        score = _fuzzy_match(str(a), str(b))
        status = "match" if score >= threshold else "mismatch"
        return {"label": label, "status": status, "website": a, "osm": b, "similarity": round(score, 2)}

    def _field_exact(label, a, b, matcher):
        if not a and not b:
            return {"label": label, "status": "no_data", "website": a, "osm": b}
        if not a or not b:
            return {"label": label, "status": "unverifiable", "website": a, "osm": b}
        status = "match" if matcher(str(a), str(b)) else "mismatch"
        return {"label": label, "status": status, "website": a, "osm": b}

    w = website or {}
    o = osm or {}
    # Phone and hours use dedicated matchers (digit-comparison, time-token
    # comparison) rather than generic string similarity -- fuzzy string
    # matching scores structurally-different phone/hours strings as
    # deceptively similar (e.g. two different time ranges sharing most
    # characters), which would silently mask real mismatches.
    fields["phone"] = _field_exact("Phone", w.get("phone"), o.get("phone"), _phones_match)
    fields["address"] = _field_fuzzy("Address", w.get("address"), o.get("address"), threshold=0.5)
    fields["hours"] = _field_exact("Opening hours", w.get("opening_hours"), o.get("opening_hours"), _hours_match)

    n_checked = sum(1 for f in fields.values() if f["status"] not in ("no_data",))
    n_ok = sum(1 for f in fields.values() if f["status"] in ("match", "ok"))
    trust_score = round(100 * n_ok / n_checked) if n_checked else 0

    return {"fields": fields, "trust_score": trust_score}


def draft_outreach_message(business_name: str, audit: dict, api_key: str, model: str) -> str:
    """Turns a freshness-audit result into a short, polite verification
    message a business could be sent -- mirrors this app's existing
    ai_lane_assist_narration() pattern (same Anthropic Messages call,
    same fail-quiet-and-fall-back behavior)."""
    if not api_key:
        return ""
    mismatches = [f["label"] for f in audit["fields"].values() if f["status"] in ("mismatch", "flag")]
    if not mismatches:
        return ""
    try:
        prompt = (
            f"Write a short, polite message (2-3 sentences) to the business "
            f"'{business_name}' asking them to confirm or correct the following "
            f"listing details, which appear inconsistent across sources: "
            f"{', '.join(mismatches)}. Keep it friendly and low-pressure, like a "
            f"routine data-verification check-in, not an accusation."
        )
        body = {"model": model, "max_tokens": 200, "messages": [{"role": "user", "content": prompt}]}
        headers = {"x-api-key": api_key, "anthropic-version": "2023-06-01", "content-type": "application/json"}
        resp = _session.post(ANTHROPIC_MESSAGES_URL, json=body, headers=headers, timeout=30)
        data = safe_json(resp, "Anthropic")
        if resp.status_code != 200:
            return ""
        return " ".join(c.get("text", "") for c in data.get("content", []) if c.get("type") == "text").strip()
    except Exception:
        return ""


# --- Step 5: gap statement (add this key to your existing TAB_GAP_STATEMENTS dict) ---
FRESHNESS_GAP_STATEMENT = (
    "**Gap addressed -- Listing Data Trust:** business hours, phone numbers, and "
    "open/closed status drift out of date between when a business changes them and "
    "when Maps reflects it. This cross-checks a business's Yelp listing against an "
    "independent OpenStreetMap record, flags mismatches with a per-field confidence "
    "score, and can draft a polite verification message to send the business -- "
    "closing the loop from detection to correction, not just flagging problems."
)


# ============================================================
# Step 6: paste this whole block at the end of your file,
# after the "with tab7:" block, replacing "with tab8:" below.
# ============================================================
"""
with tab8:
    st.info(FRESHNESS_GAP_STATEMENT)
    st.caption(
        "Compares a business's own website (via schema.org JSON-LD structured data) "
        "against an independent OpenStreetMap record. Both sources are free and need "
        "no signup or billing -- chosen specifically because commercial listing APIs "
        "(Yelp, Foursquare) either don't cover India well or paywall exactly the field "
        "(hours) this audit needs. The comparison logic itself is source-agnostic -- "
        "swapping in Google Places later needs no changes to compare_listings()."
    )

    t8c1, t8c2 = st.columns([2, 1])
    with t8c1:
        t8_business = st.text_input(
            "Business name", key="t8_business",
            placeholder="e.g. Cafe Coffee Day, Bhubaneswar",
        )
    with t8c2:
        t8_near = st.text_input("Near / city", key="t8_near", value="Bhubaneswar, India")

    t8_website_url = st.text_input(
        "Business website URL", key="t8_website_url",
        placeholder="e.g. https://www.example-cafe.com",
        help="Needs to be the business's own site. Most modern sites embed schema.org "
             "JSON-LD structured data for SEO -- if this one doesn't, the audit will "
             "still run using OSM alone and note the missing source.",
    )

    anthropic_key_t8 = get_anthropic_key()
    t8_draft_outreach = st.checkbox(
        "Also draft a verification message for flagged mismatches (needs ANTHROPIC_API_KEY)",
        value=bool(anthropic_key_t8), key="t8_draft_outreach",
    )

    if st.button("Run freshness audit", type="primary", key="t8_run"):
        if not t8_business.strip():
            st.error("Enter a business name first.")
        else:
            try:
                with st.spinner("Geocoding area..."):
                    area_lat, area_lng, _ = geocode(t8_near)

                website_listing = None
                if t8_website_url.strip():
                    with st.spinner("Reading business website..."):
                        try:
                            website_listing = fetch_website_listing(t8_website_url.strip())
                        except Exception as e:
                            st.warning(f"Website check failed: {e}")

                with st.spinner("Checking OpenStreetMap..."):
                    osm_listing = fetch_osm_listing(t8_business, area_lat, area_lng)

                if not website_listing and not osm_listing:
                    st.warning(
                        f"Couldn't find data for '{t8_business}' from either source. "
                        "If you supplied a website URL, check it loads and has structured "
                        "data (view page source, search for 'application/ld+json'). "
                        "OSM coverage is volunteer-contributed and varies by area."
                    )
                else:
                    audit = compare_listings(website_listing, osm_listing)
                    score = audit["trust_score"]

                    if not website_listing:
                        st.info(
                            "No website data available -- showing OSM data only. "
                            "Add a website URL above for a real cross-check."
                        )
                    elif score >= 80:
                        st.success(f"✅ **Trust score: {score}/100** -- listing looks consistent.")
                    elif score >= 50:
                        st.warning(f"⚠️ **Trust score: {score}/100** -- some fields don't match.")
                    else:
                        st.error(f"❌ **Trust score: {score}/100** -- significant mismatches found.")

                    status_icons = {
                        "match": "✅", "ok": "✅", "mismatch": "⚠️",
                        "flag": "🚩", "unverifiable": "❔", "no_data": "⬜",
                    }
                    rows = []
                    for f in audit["fields"].values():
                        rows.append({
                            "Field": f["label"],
                            "Status": f"{status_icons.get(f['status'], '')} {f['status'].replace('_', ' ')}",
                            "Website says": f.get("website") or "--",
                            "OSM says": f.get("osm") or "--",
                        })
                    st.dataframe(rows, use_container_width=True, hide_index=True)

                    if t8_draft_outreach and anthropic_key_t8:
                        mismatched = [f["label"] for f in audit["fields"].values() if f["status"] in ("mismatch", "flag")]
                        if mismatched:
                            with st.spinner("Drafting verification message..."):
                                message = draft_outreach_message(
                                    t8_business, audit, anthropic_key_t8, DEFAULT_VLM_MODEL,
                                )
                            if message:
                                st.subheader("✉️ Drafted verification message")
                                st.info(message)
                                st.caption(
                                    "Draft only -- this app does not send anything. In production, "
                                    "this would route to a human-reviewed outreach queue, not "
                                    "auto-send, since a wrong flag sent directly to a business "
                                    "owner erodes trust fast."
                                )
                        else:
                            st.caption("No mismatches to draft outreach for -- listing looks consistent.")
                    elif t8_draft_outreach and not anthropic_key_t8:
                        st.caption(
                            "No ANTHROPIC_API_KEY found -- add one to enable outreach drafting "
                            "(get a key at https://console.anthropic.com/settings/keys)."
                        )
            except Exception as e:
                st.error(str(e))

    with st.expander("ℹ️ Why website + OSM instead of Yelp/Google Places?"):
        st.caption(
            "Yelp Fusion's coverage is concentrated in ~32 markets, overwhelmingly US/Canada -- "
            "it has near-zero data for Indian businesses, which would make this tab look broken "
            "rather than just imperfect. Foursquare's free tier excludes exactly the field this "
            "audit needs (opening hours are a 'Premium' field billed from the first call). "
            "Google Places has the best coverage but requires a Cloud billing account on file. "
            "So this tab uses two genuinely free, global sources instead: the business's own "
            "website (schema.org structured data) and OpenStreetMap. The comparison logic in "
            "compare_listings() only cares about receiving a "
            "{name, phone, address, opening_hours} dict from each side -- so swapping in Google "
            "Places for either source later is a one-function change, not a rewrite."
        )
"""