# -*- coding: utf-8 -*-
"""APP.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ysyxe-efvKwoto7zQAMT7ozkWe9DnZFH
"""

import os
import json
import math
import random
import time
import threading
from typing import List, Optional

import requests
from requests.adapters import HTTPAdapter, Retry
import polyline
import pydeck as pdk
import streamlit as st
from dotenv import load_dotenv

load_dotenv()

# Shared session with automatic retries/backoff for transient network errors
# on OpenRouteService / Wikipedia. Nominatim gets its own, gentler handling
# below because hammering an already-429'd geocoder with more retries just
# makes things worse.
_session = requests.Session()
_retry = Retry(
    total=3, backoff_factor=0.5,
    status_forcelist=[500, 502, 503, 504],
    allowed_methods=["GET", "POST"],
)
_session.mount("https://", HTTPAdapter(max_retries=_retry))
_session.mount("http://", HTTPAdapter(max_retries=_retry))

# --- Nominatim rate limiting -------------------------------------------------
# Nominatim's usage policy caps free public usage at ~1 request/second per
# client, and hosts that share an outbound IP (Streamlit Community Cloud,
# Colab, etc.) can trip that limit even when THIS app is well-behaved,
# because *other* apps on the same IP are also calling it. We enforce our
# own >=1.1s gap between calls, and fall back to Photon (a free, keyless
# OSM-data mirror run by Komoot) if Nominatim itself is throttling us.
_nominatim_lock = threading.Lock()
_last_nominatim_call = [0.0]
_NOMINATIM_MIN_INTERVAL_S = 1.1

GEOAPIFY_URL = "https://api.geoapify.com/v1/geocode/search"

PHOTON_URL = "https://photon.komoot.io/api/"

ORS_DIRECTIONS_URL_TMPL = "https://api.openrouteservice.org/v2/directions/{profile}/geojson"
NOMINATIM_URL = "https://nominatim.openstreetmap.org/search"
WIKI_API = "https://en.wikipedia.org/w/api.php"
OPEN_METEO_URL = "https://api.open-meteo.com/v1/forecast"

# WMO weather codes (used by Open-Meteo) collapsed into plain descriptions.
_WMO_CODE_DESC = {
    0: "clear sky", 1: "mainly clear", 2: "partly cloudy", 3: "overcast",
    45: "fog", 48: "depositing rime fog",
    51: "light drizzle", 53: "drizzle", 55: "dense drizzle",
    61: "light rain", 63: "rain", 65: "heavy rain",
    71: "light snow", 73: "snow", 75: "heavy snow",
    80: "light rain showers", 81: "rain showers", 82: "violent rain showers",
    95: "thunderstorm",
}

REQUEST_HEADERS = {"User-Agent": "MapQuestSuite/1.0 (educational demo project)"}

PROFILES = {
    "Driving": "driving-car",
    "Cycling": "cycling-regular",
    "Walking": "foot-walking",
}

AVOID_OPTIONS_BY_PROFILE = {
    "driving-car": {"Highways": "highways", "Tolls": "tollways", "Ferries": "ferries"},
    "cycling-regular": {"Ferries": "ferries", "Steps": "steps"},
    "foot-walking": {"Ferries": "ferries", "Steps": "steps"},
}

# Context presets for the one-tap mode picker -- maps a mood/need to a full
# bundle of routing settings so the person doesn't have to configure each
# slider/checkbox individually (decision-fatigue removal).
CONTEXT_PRESETS = {
    "🏃 In a rush": {
        "mode": "Driving", "avoid": [], "base_g": 120, "elev_g": 1.5, "stop_g": 15,
    },
    "😴 Tired / conserve energy": {
        "mode": "Driving", "avoid": ["Highways"], "base_g": 100, "elev_g": 3.0, "stop_g": 25,
    },
    "🚶 Exploring / no rush": {
        "mode": "Walking", "avoid": [], "base_g": 0, "elev_g": 0.0, "stop_g": 0,
    },
}

# Rough, editable cost assumptions for the multi-modal cost optimizer.
# These are NOT live fares -- free routing APIs don't expose real-time
# rideshare/transit pricing -- they're transparent, adjustable estimates so
# people can compare modes on the same trip.
COST_ASSUMPTIONS = {
    "driving-car": {"label": "🚗 Driving", "per_km": 8.0, "flat_fee": 0.0},
    "cycling-regular": {"label": "🚲 Cycling (own bike)", "per_km": 0.0, "flat_fee": 0.0},
    "foot-walking": {"label": "🚶 Walking", "per_km": 0.0, "flat_fee": 0.0},
}

# ORS maneuver 'type' codes that correspond to a stop / yield / signal point.
STOP_LIKE_MANEUVER_TYPES = {0, 1, 2, 3, 4, 5, 7, 8, 9, 12, 13}


def get_ors_key() -> str:
    try:
        if "ORS_API_KEY" in st.secrets:
            return st.secrets["ORS_API_KEY"]
    except Exception:
        pass
    return os.getenv("ORS_API_KEY", "")


def get_geoapify_key() -> str:
    """Optional. If set, Geoapify (free tier, 3000 req/day, no card) becomes
    the PRIMARY geocoder, since Nominatim's shared free endpoint gets
    rate-limited on cloud hosts regardless of how careful this app is."""
    try:
        if "GEOAPIFY_API_KEY" in st.secrets:
            return st.secrets["GEOAPIFY_API_KEY"]
    except Exception:
        pass
    return os.getenv("GEOAPIFY_API_KEY", "")


def safe_json(resp: requests.Response, source: str) -> dict:
    try:
        return resp.json()
    except Exception:
        snippet = resp.text[:200].replace("\n", " ") if resp.text else "(empty body)"
        raise RuntimeError(f"{source} returned a non-JSON response (HTTP {resp.status_code}): {snippet}")


# ============================================================
# Shared helpers
# ============================================================

class RouteResult:
    """
    Plain class with an explicit __init__ (deliberately NOT a @dataclass).
    Some deployment/build pipelines strip decorators they don't recognize,
    which silently turns a dataclass into a bare class with no generated
    __init__ -- and calling it with keyword arguments then raises
    'RouteResult() takes no arguments'. Writing __init__ by hand avoids
    that failure mode entirely, at the cost of a few extra lines.
    """

    def __init__(
        self,
        summary: str,
        distance_m: float,
        duration_s: float,
        duration_in_traffic_s: Optional[float],
        stop_count: int,
        polyline_points: List[List[float]],
        encoded_polyline: str,
        elevation_profile: Optional[List[float]] = None,
        elevation_gain_m: float = 0.0,
        co2_grams: float = 0.0,
        origin_country: Optional[str] = None,
        destination_country: Optional[str] = None,
    ):
        self.summary = summary
        self.distance_m = distance_m
        self.duration_s = duration_s
        self.duration_in_traffic_s = duration_in_traffic_s
        self.stop_count = stop_count
        self.polyline_points = polyline_points
        self.encoded_polyline = encoded_polyline
        self.elevation_profile = elevation_profile if elevation_profile is not None else []
        self.elevation_gain_m = elevation_gain_m
        self.co2_grams = co2_grams
        self.origin_country = origin_country
        self.destination_country = destination_country

    @property
    def is_international(self) -> bool:
        return bool(
            self.origin_country
            and self.destination_country
            and self.origin_country != self.destination_country
        )


def _throttled_nominatim_get(params: dict) -> requests.Response:
    """Enforce our own >=1.1s gap before hitting Nominatim, since the shared
    cloud IP may already be close to its rate limit from other apps."""
    with _nominatim_lock:
        elapsed = time.monotonic() - _last_nominatim_call[0]
        if elapsed < _NOMINATIM_MIN_INTERVAL_S:
            time.sleep(_NOMINATIM_MIN_INTERVAL_S - elapsed)
        resp = requests.get(NOMINATIM_URL, params=params, headers=REQUEST_HEADERS, timeout=15)
        _last_nominatim_call[0] = time.monotonic()
        return resp


def _geocode_photon(place: str) -> Optional[tuple]:
    """Fallback geocoder: free, keyless, OSM-data mirror. Used only when
    Nominatim itself is rate-limiting us, not as a first choice."""
    try:
        resp = _session.get(PHOTON_URL, params={"q": place, "limit": 1},
                             headers=REQUEST_HEADERS, timeout=15)
        data = safe_json(resp, "Photon geocoding")
        features = data.get("features", [])
        if not features:
            return None
        feat = features[0]
        lng, lat = feat["geometry"]["coordinates"]
        country = feat.get("properties", {}).get("country")
        return float(lat), float(lng), country
    except Exception:
        return None


def _geocode_geoapify(place: str, api_key: str) -> Optional[tuple]:
    try:
        resp = _session.get(GEOAPIFY_URL, params={"text": place, "limit": 1, "apiKey": api_key},
                             headers=REQUEST_HEADERS, timeout=15)
        data = safe_json(resp, "Geoapify geocoding")
        features = data.get("features", [])
        if not features:
            return None
        props = features[0].get("properties", {})
        lat, lng = props.get("lat"), props.get("lon")
        if lat is None or lng is None:
            return None
        return float(lat), float(lng), props.get("country")
    except Exception:
        return None


@st.cache_data(ttl=3600, show_spinner=False)
def geocode(place: str) -> tuple:
    """Returns (lat, lng, country_name_or_None). Cached for 1h since a given
    place name always resolves to the same point.

    Provider order:
      1. Geoapify (if GEOAPIFY_API_KEY is configured) -- free tier, keyed,
         not subject to the shared-IP throttling that hits Nominatim on
         cloud hosts. This is the recommended primary provider.
      2. Nominatim, self-throttled to >=1.1s between calls.
      3. Photon (Komoot's free, keyless OSM mirror) as a last resort.
    """
    geoapify_key = get_geoapify_key()
    if geoapify_key:
        result = _geocode_geoapify(place, geoapify_key)
        if result is not None:
            return result
        # Geoapify failed for some reason -- fall through to the free chain
        # rather than giving up immediately.

    try:
        resp = _throttled_nominatim_get(
            {"q": place, "format": "json", "limit": 1, "addressdetails": 1}
        )
        if resp.status_code == 429:
            raise RuntimeError("Nominatim rate-limited us (429)")
        results = safe_json(resp, "Nominatim geocoding")
        if results:
            result = results[0]
            country = result.get("address", {}).get("country")
            return float(result["lat"]), float(result["lon"]), country
    except Exception:
        pass  # fall through to Photon below

    # Nominatim failed or rate-limited us -- try the Photon mirror instead
    # of failing outright.
    fallback = _geocode_photon(place)
    if fallback is not None:
        return fallback

    raise RuntimeError(f"Could not geocode '{place}' -- try a more specific place name.")


def compute_elevation_gain(profile: List[float]) -> float:
    gain = 0.0
    for prev, curr in zip(profile, profile[1:]):
        if curr - prev > 0:
            gain += curr - prev
    return gain


def circle_polygon(lat: float, lng: float, radius_m: float, n_points: int = 16) -> List[List[float]]:
    """Approximate a circle as a closed polygon ring [[lng, lat], ...] for avoid_polygons."""
    R = 6371000.0
    lat_rad = math.radians(lat)
    ring = []
    for i in range(n_points):
        angle = 2 * math.pi * i / n_points
        dlat = (radius_m * math.cos(angle)) / R
        dlng = (radius_m * math.sin(angle)) / (R * math.cos(lat_rad))
        ring.append([lng + math.degrees(dlng), lat + math.degrees(dlat)])
    ring.append(ring[0])
    return ring


def build_avoid_polygons(hazard_zones: List[dict]) -> Optional[dict]:
    if not hazard_zones:
        return None
    polygons = [[circle_polygon(z["lat"], z["lng"], z["radius_m"])] for z in hazard_zones]
    return {"type": "MultiPolygon", "coordinates": polygons}


def _fetch_single_route(
    coords_lnglat: List[List[float]], profile: str, preference: str,
    avoid_features: List[str], avoid_polygons: Optional[dict], ors_key: str,
) -> Optional[dict]:
    body = {
        "coordinates": coords_lnglat,
        "elevation": True,
        "instructions": True,
        "preference": preference,
    }
    options = {}
    if avoid_features:
        options["avoid_features"] = avoid_features
    if avoid_polygons:
        options["avoid_polygons"] = avoid_polygons
    if options:
        body["options"] = options

    url = ORS_DIRECTIONS_URL_TMPL.format(profile=profile)
    headers = {"Authorization": ors_key, "Content-Type": "application/json"}
    resp = _session.post(url, json=body, headers=headers, timeout=20)
    data = safe_json(resp, "OpenRouteService")
    if resp.status_code != 200:
        msg = data.get("error", {}).get("message", str(data))
        # ORS returns 2010 'routable point not found' / 2004 'unable to find
        # a route between points' when the profile can't bridge the gap --
        # most commonly because it would require crossing an ocean.
        if resp.status_code in (404, 500) and ("route" in msg.lower() or "point" in msg.lower()):
            raise RuntimeError(
                "No route found between these points for the selected travel mode. "
                "This usually means the two locations aren't connected by road/path/cycleway "
                "(e.g. they're on different continents separated by ocean, with no ferry link "
                "in the routing data). Try a route within the same landmass, or pick a "
                "different travel mode."
            )
        raise RuntimeError(f"OpenRouteService error: {msg}")
    features = data.get("features", [])
    return features[0] if features else None


def fetch_routes(
    waypoint_addresses: List[str], profile: str = "driving-car",
    avoid_features: Optional[List[str]] = None,
    hazard_zones: Optional[List[dict]] = None,
    ors_key: str = "",
) -> List[RouteResult]:
    avoid_features = avoid_features or []
    avoid_polygons = build_avoid_polygons(hazard_zones or [])

    coords_lnglat = []
    countries = []
    for addr in waypoint_addresses:
        lat, lng, country = geocode(addr)
        coords_lnglat.append([lng, lat])
        countries.append(country)

    origin_country = countries[0]
    destination_country = countries[-1]

    preferences = [("recommended", "Recommended route"), ("shortest", "Shortest route")]
    results = []
    seen_distances = set()
    for preference, label in preferences:
        feature = _fetch_single_route(coords_lnglat, profile, preference, avoid_features, avoid_polygons, ors_key)
        if feature is None:
            continue
        props = feature["properties"]
        summary = props.get("summary", {})
        distance_m = summary.get("distance", 0.0)

        rounded = round(distance_m, -2)
        if rounded in seen_distances:
            continue
        seen_distances.add(rounded)

        duration_s = summary.get("duration", 0.0)
        stop_count = 0
        for segment in props.get("segments", []):
            for step in segment.get("steps", []):
                if step.get("type") in STOP_LIKE_MANEUVER_TYPES:
                    stop_count += 1

        coords = feature["geometry"]["coordinates"]
        points = [[c[1], c[0]] for c in coords]
        elevation_profile = [c[2] for c in coords if len(c) > 2]
        encoded = polyline.encode([(lat, lng) for lat, lng in points])

        r = RouteResult(
            summary=label, distance_m=distance_m, duration_s=duration_s,
            duration_in_traffic_s=None, stop_count=stop_count,
            polyline_points=points, encoded_polyline=encoded,
            elevation_profile=elevation_profile,
            origin_country=origin_country, destination_country=destination_country,
        )
        r.elevation_gain_m = compute_elevation_gain(elevation_profile)
        results.append(r)

    if not results:
        raise RuntimeError("No routes returned -- try different locations or fewer restrictions.")
    return results


def sample_points(points: List[List[float]], max_samples: int = 100) -> List[List[float]]:
    if len(points) <= max_samples:
        return points
    step = len(points) / max_samples
    return [points[int(i * step)] for i in range(max_samples)]


@st.cache_data(ttl=3600, show_spinner=False)
def wiki_geosearch(lat: float, lng: float, radius_m: int) -> list:
    """Nearby Wikipedia pages around a point. Cached since the same
    place+radius always returns the same nearby articles."""
    raw = _session.get(WIKI_API, params={
        "action": "query", "list": "geosearch", "gscoord": f"{lat}|{lng}",
        "gsradius": radius_m, "gslimit": 6, "format": "json",
    }, headers=REQUEST_HEADERS, timeout=15)
    resp = safe_json(raw, "Wikipedia geosearch")
    return resp.get("query", {}).get("geosearch", [])


@st.cache_data(ttl=3600, show_spinner=False)
def wiki_page_details(titles_pipe_joined: str) -> dict:
    """Extracts + thumbnails for a '|'-joined list of page titles. Cached
    per unique title set."""
    raw = _session.get(WIKI_API, params={
        "action": "query", "prop": "extracts|pageimages", "exintro": True,
        "explaintext": True, "piprop": "thumbnail", "pithumbsize": 400,
        "titles": titles_pipe_joined, "format": "json",
    }, headers=REQUEST_HEADERS, timeout=15)
    resp = safe_json(raw, "Wikipedia page details")
    return resp.get("query", {}).get("pages", {})


def truncate_at_word(text: str, max_len: int = 400) -> str:
    """Truncate to max_len chars without cutting a word in half."""
    if len(text) <= max_len:
        return text
    cut = text[:max_len].rsplit(" ", 1)[0]
    return cut + "..."


@st.cache_data(ttl=600, show_spinner=False)
def fetch_weather(lat: float, lng: float) -> Optional[dict]:
    """Current conditions at a point, via Open-Meteo (free, no API key).
    Cached for 10 min since weather doesn't need per-second freshness."""
    try:
        resp = _session.get(OPEN_METEO_URL, params={
            "latitude": lat, "longitude": lng,
            "current": "temperature_2m,wind_speed_10m,precipitation,weather_code",
            "timezone": "auto",
        }, headers=REQUEST_HEADERS, timeout=15)
        data = safe_json(resp, "Open-Meteo")
        current = data.get("current", {})
        if not current:
            return None
        code = current.get("weather_code")
        return {
            "temp_c": current.get("temperature_2m"),
            "wind_kmh": current.get("wind_speed_10m"),
            "precip_mm": current.get("precipitation"),
            "description": _WMO_CODE_DESC.get(code, "unknown conditions"),
        }
    except Exception:
        return None


# Thresholds for treating a sampled point as an active routing hazard, as
# opposed to just an advisory note. Deliberately stricter than
# weather_route_advice()'s thresholds -- we only want to spend a reroute on
# conditions that plausibly change which road is the right choice, not
# every point that's merely "a bit windy".
_HAZARD_ICE_MAX_TEMP_C = 2.0
_HAZARD_ICE_MIN_PRECIP_MM = 0.5
_HAZARD_WIND_KMH = 45.0
_HAZARD_HEAVY_PRECIP_MM = 4.0
_HAZARD_HEAT_C = 40.0
_HAZARD_ZONE_RADIUS_M = 900


def classify_weather_hazard(weather: dict) -> Optional[dict]:
    """Returns a single dominant hazard {"type", "note"} for one sampled
    point if conditions cross a routing-relevant threshold, else None.
    Checked in rough order of how dangerous/route-changing each is."""
    if not weather:
        return None
    temp = weather.get("temp_c")
    wind = weather.get("wind_kmh")
    precip = weather.get("precip_mm")

    if temp is not None and precip is not None and temp <= _HAZARD_ICE_MAX_TEMP_C and precip >= _HAZARD_ICE_MIN_PRECIP_MM:
        return {"type": "ice_risk", "note": f"possible icing ({temp:.0f}°C with active precipitation)"}
    if wind is not None and wind >= _HAZARD_WIND_KMH:
        return {"type": "high_wind", "note": f"high wind gusts (~{wind:.0f} km/h)"}
    if precip is not None and precip >= _HAZARD_HEAVY_PRECIP_MM:
        return {"type": "heavy_precip", "note": f"heavy precipitation ({precip:.1f} mm)"}
    if temp is not None and temp >= _HAZARD_HEAT_C:
        return {"type": "extreme_heat", "note": f"extreme heat ({temp:.0f}°C)"}
    return None


def sample_weather_hazards_along_route(points: List[List[float]], max_samples: int = 8) -> List[dict]:
    """Fetches (cached) weather at a handful of evenly-spaced points along a
    route and returns only the ones that cross a hazard threshold, each
    shaped like a hazard_zone entry so it can feed straight into
    build_avoid_polygons() alongside community-reported hazards."""
    sampled = sample_points(points, max_samples=max_samples)
    hazards = []
    for lat, lng in sampled:
        weather = fetch_weather(lat, lng)
        hazard = classify_weather_hazard(weather)
        if hazard:
            hazards.append({
                "lat": lat, "lng": lng, "radius_m": _HAZARD_ZONE_RADIUS_M,
                "type": hazard["type"], "note": hazard["note"],
            })
    return hazards


def explain_weather_reroute(baseline: RouteResult, alt: Optional[RouteResult], hazards: List[dict]) -> str:
    """Plain-English trade-off explanation -- this is the piece Google Maps
    itself doesn't surface: not just 'here's a route' but 'here's why we'd
    pick a different one than the fastest option right now'."""
    if not hazards:
        return "No active weather hazards detected along this route -- fastest route is also the weather-safe one."
    reasons = "; ".join(sorted({h["note"] for h in hazards}))
    if alt is None or alt.encoded_polyline == baseline.encoded_polyline:
        return (
            f"Detected {reasons} along the route, but no viable detour avoids it "
            f"(likely a single-road corridor) -- proceed with caution on the affected stretch."
        )
    extra_km = (alt.distance_m - baseline.distance_m) / 1000.0
    extra_min = (alt.duration_s - baseline.duration_s) / 60.0
    return (
        f"Rerouted around {reasons}. This costs **+{max(extra_km, 0):.1f} km / "
        f"+{max(extra_min, 0):.0f} min** versus the fastest route, in exchange for avoiding "
        f"the flagged hazard zone(s)."
    )


def estimate_mode_cost(profile: str, distance_m: float, duration_s: float) -> float:
    """Rough, transparent cost estimate for a mode -- NOT a live fare quote.
    Free routing APIs don't expose real-time rideshare/transit pricing."""
    cfg = COST_ASSUMPTIONS.get(profile, {"per_km": 0.0, "flat_fee": 0.0})
    return cfg["flat_fee"] + (distance_m / 1000.0) * cfg["per_km"]


def render_international_badge(route: RouteResult):
    if route.is_international:
        st.info(f"🌍 International route: **{route.origin_country} → {route.destination_country}**")


# ============================================================
# Streamlit page setup
# ============================================================

st.set_page_config(page_title="MapQuest Suite", layout="wide")
st.title("🗺️ MapQuest Suite")
st.caption(
    "One thesis, five demonstrations: mainstream mapping optimizes for distance and "
    "historical traffic, but stays silent on *why* a route is best, ignores live "
    "conditions until it's too late to matter, and treats every rider identically. "
    "Each tab below targets one specific, named gap -- built on free, no-credit-card APIs."
)

TAB_GAP_STATEMENTS = {
    "🌱 Greenest Route": "**Gap addressed -- Route Trade-Off Clarity:** rather than a single black-box "
                          "'recommended' route, this reroutes around live weather hazards and community-"
                          "reported closures, then explains the exact cost of that choice in km/min.",
    "👻 Ghost Jam Predictor": "**Gap addressed -- Delayed Real-Time Anomaly Routing:** mainstream apps react "
                              "to traffic after it forms from historical data; this models *why* phantom jams "
                              "emerge from following/braking behavior, which is predictive, not reactive.",
    "🕰️ AR Local History": "**Gap addressed -- Frictionless Discovery:** surfaces contextual, place-anchored "
                           "knowledge (historical/cultural context) that keyword-and-review search misses "
                           "entirely, without requiring a phone-camera AR view.",
    "📡 Offline Navigator": "**Gap addressed -- Connectivity Resilience:** most navigation assumes constant "
                            "connectivity; this shows a route can be compressed small enough to transmit over "
                            "SMS/Bluetooth for low-connectivity or emergency scenarios.",
    "🧘 Sensory & Safety Router": "**Gap addressed -- Precise, Personalized Guidance:** one-size-fits-all ETAs "
                                  "ignore that the same route can be a poor fit for a given person or time of "
                                  "day; this scores routes for sensory load and night-safety instead.",
}

ORS_KEY = get_ors_key()
ORS_KEY_MISSING_MSG = (
    "No ORS_API_KEY found. Get a free key (no card needed) at "
    "https://openrouteservice.org/dev/#/signup -- then locally put it in a .env file, "
    "or on Streamlit Community Cloud add it under Settings > Secrets as:\n"
    'ORS_API_KEY = "your_real_key_here"'
)
# Don't st.stop() the whole app here -- Tab 3 (AR Local History) only calls
# Wikipedia/Nominatim and works fine with no ORS key at all. Each
# ORS-dependent tab checks ORS_KEY itself before running.

if not get_geoapify_key():
    st.caption(
        "💡 Geocoding currently relies on Nominatim's free public endpoint, which can get "
        "rate-limited on shared cloud IPs (Streamlit Cloud, Colab, etc.). For reliable "
        "geocoding, get a free Geoapify key (no card, 3000 req/day) at "
        "https://www.geoapify.com/get-started-with-maps-api and add it as GEOAPIFY_API_KEY "
        "in Secrets or your .env file."
    )

if "hazard_zones" not in st.session_state:
    st.session_state.hazard_zones = []
if "community_notes" not in st.session_state:
    # Broader crowdsourced layer: only entries tagged "🚧 Hazard/Closure"
    # actually affect routing (mirrored into hazard_zones below); the rest
    # (lighting, accessibility, tips) are informational map pins only.
    st.session_state.community_notes = []

NOTE_CATEGORIES = {
    "🚧 Hazard/Closure": {"affects_routing": True, "color": [220, 30, 30, 200]},
    "💡 Broken lighting": {"affects_routing": False, "color": [255, 200, 0, 200]},
    "♿ Accessibility issue": {"affects_routing": False, "color": [30, 100, 220, 200]},
    "🎒 Local tip": {"affects_routing": False, "color": [30, 180, 90, 200]},
}

tab1, tab2, tab3, tab4, tab5 = st.tabs([
    "🌱 Greenest Route",
    "👻 Ghost Jam Predictor",
    "🕰️ AR Local History",
    "📡 Offline Navigator",
    "🧘 Sensory & Safety Router",
])

# ============================================================
# TAB 1 -- Greenest Route Optimizer (advanced routing + hazard avoidance)
# ============================================================
with tab1:
    st.info(TAB_GAP_STATEMENTS["🌱 Greenest Route"])

    def _apply_context_preset():
        preset = CONTEXT_PRESETS.get(st.session_state.get("t1_preset"))
        if not preset:
            return
        st.session_state["t1_mode"] = preset["mode"]
        st.session_state["t1_avoid"] = preset["avoid"]
        st.session_state["t1_base"] = preset["base_g"]
        st.session_state["t1_elev"] = preset["elev_g"]
        st.session_state["t1_stop"] = preset["stop_g"]

    st.radio(
        "How are you traveling right now? (one-tap preset -- fills in mode + weights below; adjust anything afterward)",
        list(CONTEXT_PRESETS.keys()), index=None, horizontal=True,
        key="t1_preset", on_change=_apply_context_preset,
    )

    c1, c2 = st.columns(2)
    with c1:
        origin1 = st.text_input("Origin", value="Bhubaneswar, India", key="t1_origin")
    with c2:
        destination1 = st.text_input("Destination", value="Puri, India", key="t1_dest")

    with st.expander("🚗 Routing options"):
        mode_label = st.radio("Travel mode", list(PROFILES.keys()), horizontal=True, key="t1_mode")
        profile = PROFILES[mode_label]

        avoid_map = AVOID_OPTIONS_BY_PROFILE[profile]
        avoid_labels = st.multiselect("Avoid", list(avoid_map.keys()), key="t1_avoid")
        avoid_features = [avoid_map[label] for label in avoid_labels]

        waypoints_text = st.text_area(
            "Extra stops (optional, one per line, visited in order)",
            placeholder="e.g.\nChandaka Wildlife Sanctuary\nPipili",
            key="t1_waypoints",
        )

        st.caption("CO2 model weights (assumptions, not official emission factors)")
        wc1, wc2, wc3 = st.columns(3)
        with wc1:
            base_g_per_km = st.slider("g CO2 / km", 0, 250, 120, key="t1_base")
        with wc2:
            elevation_g_per_m = st.slider("g CO2 / m climbed", 0.0, 5.0, 1.5, key="t1_elev")
        with wc3:
            stop_g_per_stop = st.slider("g CO2 / stop", 0, 50, 15, key="t1_stop")

    with st.expander("📌 Community Notes (crowdsourced hazards, lighting, access, tips)"):
        st.caption(
            "A local-knowledge layer most mainstream mapping apps don't have: only **🚧 Hazard/Closure** "
            "notes actually reroute you around them; the rest are informational pins. "
            "Session-only for this demo -- not shared across users or saved between restarts."
        )
        nc1, nc2, nc3, nc4 = st.columns([3, 2, 1, 1])
        with nc1:
            note_place = st.text_input("Place name", key="note_place", label_visibility="collapsed", placeholder="Place name")
        with nc2:
            note_category = st.selectbox("Category", list(NOTE_CATEGORIES.keys()), key="note_category", label_visibility="collapsed")
        with nc3:
            note_radius = st.number_input("Radius (m)", 20, 20000, 300, key="note_radius", label_visibility="collapsed")
        with nc4:
            if st.button("Add", key="note_add"):
                try:
                    lat, lng, _ = geocode(note_place)
                    entry = {
                        "name": note_place, "lat": lat, "lng": lng,
                        "radius_m": note_radius, "category": note_category,
                    }
                    st.session_state.community_notes.append(entry)
                    if NOTE_CATEGORIES[note_category]["affects_routing"]:
                        st.session_state.hazard_zones.append(entry)
                except Exception as e:
                    st.error(str(e))

        if st.session_state.community_notes:
            for i, n in enumerate(st.session_state.community_notes):
                zc1, zc2 = st.columns([5, 1])
                with zc1:
                    routing_tag = " (affects routing)" if NOTE_CATEGORIES[n["category"]]["affects_routing"] else ""
                    st.write(f"{n['category']} **{n['name']}** -- {n['radius_m']}m radius{routing_tag}")
                with zc2:
                    if st.button("Remove", key=f"note_remove_{i}"):
                        st.session_state.community_notes.pop(i)
                        # Keep hazard_zones (routing) in sync -- rebuild it
                        # from remaining hazard-category notes.
                        st.session_state.hazard_zones = [
                            n2 for n2 in st.session_state.community_notes
                            if NOTE_CATEGORIES[n2["category"]]["affects_routing"]
                        ]
                        st.rerun()
        else:
            st.caption("No community notes added yet.")

    if not ORS_KEY:
        st.warning(ORS_KEY_MISSING_MSG)

    if st.button("Find greenest route", type="primary", key="t1_run") and ORS_KEY:
        try:
            vias = [line.strip() for line in waypoints_text.strip().splitlines() if line.strip()]
            all_stops = [origin1] + vias + [destination1]

            with st.spinner("Fetching routes..."):
                routes = fetch_routes(
                    all_stops, profile=profile, avoid_features=avoid_features,
                    hazard_zones=st.session_state.hazard_zones, ors_key=ORS_KEY,
                )

            for r in routes:
                distance_km = r.distance_m / 1000.0
                base = distance_km * base_g_per_km
                elev = r.elevation_gain_m * elevation_g_per_m
                stops = r.stop_count * stop_g_per_stop
                r.co2_grams = base + elev + stops

            routes_sorted = sorted(routes, key=lambda r: r.co2_grams)
            greenest = routes_sorted[0]

            render_international_badge(greenest)
            st.success(f"Greenest: **{greenest.summary}** (~{greenest.co2_grams/1000:.2f} kg CO2 estimated)")

            st.dataframe([{
                "Route": r.summary,
                "Distance (km)": round(r.distance_m / 1000, 2),
                "Duration (min)": round(r.duration_s / 60, 1),
                "Elevation gain (m)": round(r.elevation_gain_m, 1),
                "Stop-like turns": r.stop_count,
                "Est. CO2 (kg)": round(r.co2_grams / 1000, 3),
            } for r in routes_sorted], use_container_width=True, hide_index=True)

            layers = []
            colors = [[0, 160, 0, 200], [255, 140, 0, 160], [200, 30, 30, 160]]
            for i, r in enumerate(routes_sorted):
                color = colors[i] if i < len(colors) else [100, 100, 100, 150]
                path = [[lng, lat] for lat, lng in r.polyline_points]
                layers.append(pdk.Layer("PathLayer", data=[{"path": path}], get_path="path",
                                         get_color=color, width_scale=1, width_min_pixels=4))

            for n in st.session_state.community_notes:
                ring = circle_polygon(n["lat"], n["lng"], n["radius_m"])
                fill = NOTE_CATEGORIES[n["category"]]["color"]
                line = fill[:3] + [220]
                layers.append(pdk.Layer(
                    "PolygonLayer", data=[{"polygon": ring}], get_polygon="polygon",
                    get_fill_color=fill[:3] + [80], get_line_color=line,
                    line_width_min_pixels=2,
                ))

            mid = greenest.polyline_points[len(greenest.polyline_points) // 2]
            st.pydeck_chart(pdk.Deck(map_style="road",
                                      initial_view_state=pdk.ViewState(latitude=mid[0], longitude=mid[1], zoom=10),
                                      layers=layers))
            st.caption(
                "Green = greenest route. Red = hazard/closure (avoided). "
                "Yellow = lighting, blue = accessibility, teal = local tips (informational only)."
            )
            if greenest.elevation_profile:
                st.line_chart(greenest.elevation_profile)

            # --- Weather-safe reroute (fastest vs weather-safe trade-off) ---
            st.subheader("🌦️ Fastest vs. Weather-Safe Route")
            weather_mid = fetch_weather(mid[0], mid[1])
            if weather_mid:
                st.caption(
                    f"Currently **{weather_mid['description']}**, {weather_mid['temp_c']:.0f}°C, "
                    f"wind {weather_mid['wind_kmh']:.0f} km/h near the route midpoint."
                )

            with st.spinner("Sampling weather along the route..."):
                weather_hazards = sample_weather_hazards_along_route(greenest.polyline_points)

            weather_safe_route = None
            if weather_hazards:
                try:
                    combined_hazards = list(st.session_state.hazard_zones) + weather_hazards
                    with st.spinner("Computing weather-safe alternative..."):
                        alt_routes = fetch_routes(
                            all_stops, profile=profile, avoid_features=avoid_features,
                            hazard_zones=combined_hazards, ors_key=ORS_KEY,
                        )
                    # Prefer the fastest of the alternatives that actually
                    # differs from the baseline; fall back to the baseline
                    # itself if ORS couldn't find a distinct detour.
                    distinct = [r for r in alt_routes if r.encoded_polyline != greenest.encoded_polyline]
                    weather_safe_route = min(distinct, key=lambda r: r.duration_s) if distinct else alt_routes[0]
                except Exception:
                    weather_safe_route = None  # fall through to explanation-only messaging below

            explanation = explain_weather_reroute(greenest, weather_safe_route, weather_hazards)
            if weather_hazards and weather_safe_route and weather_safe_route.encoded_polyline != greenest.encoded_polyline:
                st.warning(explanation)
            elif weather_hazards:
                st.warning(explanation)
            else:
                st.success(explanation)

            if weather_hazards:
                hz1, hz2 = st.columns(2)
                hz1.metric("⚡ Fastest route", f"{greenest.distance_m/1000:.1f} km", f"{greenest.duration_s/60:.0f} min")
                if weather_safe_route:
                    delta_km = (weather_safe_route.distance_m - greenest.distance_m) / 1000
                    delta_min = (weather_safe_route.duration_s - greenest.duration_s) / 60
                    hz2.metric("🛡️ Weather-safe route", f"{weather_safe_route.distance_m/1000:.1f} km",
                               f"+{delta_min:.0f} min" if delta_min > 0 else f"{delta_min:.0f} min")

                # Plot both so the trade-off is visible, not just stated.
                weather_layers = [pdk.Layer(
                    "PathLayer", data=[{"path": [[lng, lat] for lat, lng in greenest.polyline_points]}],
                    get_path="path", get_color=[0, 160, 0, 200], width_min_pixels=4,
                )]
                if weather_safe_route:
                    weather_layers.append(pdk.Layer(
                        "PathLayer", data=[{"path": [[lng, lat] for lat, lng in weather_safe_route.polyline_points]}],
                        get_path="path", get_color=[30, 100, 220, 200], width_min_pixels=4,
                    ))
                weather_layers.append(pdk.Layer(
                    "ScatterplotLayer",
                    data=[{"lat": h["lat"], "lng": h["lng"]} for h in weather_hazards],
                    get_position=["lng", "lat"], get_radius=_HAZARD_ZONE_RADIUS_M,
                    get_fill_color=[220, 30, 30, 60], get_line_color=[220, 30, 30, 200], stroked=True,
                ))
                st.pydeck_chart(pdk.Deck(map_style="road",
                                          initial_view_state=pdk.ViewState(latitude=mid[0], longitude=mid[1], zoom=10),
                                          layers=weather_layers))
                st.caption("🟢 Fastest route · 🔵 Weather-safe alternative · 🔴 Flagged weather-hazard zone(s)")

            # --- Multi-modal cost optimizer ----------------------------------
            with st.expander("💰 Compare cost & time across modes"):
                st.caption(
                    "Estimates only -- free routing APIs don't expose live rideshare/transit "
                    "fares, so these are transparent, editable assumptions, not real-time quotes."
                )
                cc1, cc2, cc3 = st.columns(3)
                with cc1:
                    drive_rate = st.number_input("Driving: cost per km", 0.0, 100.0,
                                                  COST_ASSUMPTIONS["driving-car"]["per_km"], key="t1_cost_drive")
                with cc2:
                    bike_rate = st.number_input("Cycling: cost per km", 0.0, 100.0,
                                                 COST_ASSUMPTIONS["cycling-regular"]["per_km"], key="t1_cost_bike")
                with cc3:
                    walk_rate = st.number_input("Walking: cost per km", 0.0, 100.0,
                                                 COST_ASSUMPTIONS["foot-walking"]["per_km"], key="t1_cost_walk")

                if st.button("Compare all modes for this trip", key="t1_compare_modes"):
                    live_rates = {
                        "driving-car": drive_rate,
                        "cycling-regular": bike_rate,
                        "foot-walking": walk_rate,
                    }
                    compare_rows = []
                    with st.spinner("Fetching routes for each mode..."):
                        for mode_profile, mode_cfg in COST_ASSUMPTIONS.items():
                            try:
                                mode_routes = fetch_routes(all_stops, profile=mode_profile, ors_key=ORS_KEY)
                                fastest = min(mode_routes, key=lambda r: r.duration_s)
                                cost = live_rates[mode_profile] * (fastest.distance_m / 1000.0)
                                compare_rows.append({
                                    "Mode": mode_cfg["label"],
                                    "Distance (km)": round(fastest.distance_m / 1000, 2),
                                    "Time (min)": round(fastest.duration_s / 60, 1),
                                    "Est. cost": round(cost, 2),
                                })
                            except Exception:
                                compare_rows.append({
                                    "Mode": mode_cfg["label"], "Distance (km)": "--",
                                    "Time (min)": "--", "Est. cost": "no route available",
                                })
                    st.dataframe(compare_rows, use_container_width=True, hide_index=True)
        except Exception as e:
            st.error(str(e))

# ============================================================
# TAB 2 -- Ghost Jam Predictor
# ============================================================
with tab2:
    st.info(TAB_GAP_STATEMENTS["👻 Ghost Jam Predictor"])
    st.caption(
        "Simulated risk model overlaid on a real route -- illustrates phantom-jam "
        "slowdowns caused by braking behavior, not a live traffic feed."
    )
    c1, c2 = st.columns(2)
    with c1:
        origin2 = st.text_input("Origin", value="Bhubaneswar, India", key="t2_origin")
    with c2:
        destination2 = st.text_input("Destination", value="Puri, India", key="t2_dest")

    hour = st.slider("Hour of day (rush-hour weighting)", 0, 23, 9, key="t2_hour")

    if not ORS_KEY:
        st.warning(ORS_KEY_MISSING_MSG)

    if st.button("Predict ghost jams", type="primary", key="t2_run") and ORS_KEY:
        try:
            with st.spinner("Fetching real route..."):
                routes = fetch_routes([origin2, destination2], ors_key=ORS_KEY)
            route = routes[0]
            render_international_badge(route)
            sampled = sample_points(route.polyline_points, max_samples=60)

            rush_factor = 0.3 + math.exp(-((hour - 8) ** 2) / 8) + math.exp(-((hour - 18) ** 2) / 8)
            random.seed(42)
            risk_points = [
                {"lat": lat, "lng": lng, "weight": random.uniform(0.2, 1.0) * rush_factor}
                for lat, lng in sampled
            ]
            st.success(f"Simulated {len(risk_points)} risk points for hour={hour}:00.")

            layer = pdk.Layer("HeatmapLayer", data=risk_points, get_position=["lng", "lat"],
                               get_weight="weight", radiusPixels=40)
            mid = sampled[len(sampled) // 2]
            st.pydeck_chart(pdk.Deck(map_style="road",
                                      initial_view_state=pdk.ViewState(latitude=mid[0], longitude=mid[1], zoom=10),
                                      layers=[layer]))

            st.subheader("Why phantom jams happen")
            n_cars = 22
            positions = sorted(random.uniform(0, 100) for _ in range(n_cars))
            speeds = [5.0] * n_cars
            history = []
            for _ in range(120):
                new_positions = []
                for i in range(n_cars):
                    gap = (positions[(i + 1) % n_cars] - positions[i]) % 100
                    target_speed = min(5.0, max(0.0, gap - 2.0))
                    speeds[i] += (target_speed - speeds[i]) * 0.3
                    new_positions.append((positions[i] + speeds[i]) % 100)
                positions = new_positions
                history.append(list(speeds))
            st.line_chart(history)
            st.caption("Each line is one simulated car's speed -- waves emerge purely from spacing/braking.")
        except Exception as e:
            st.error(str(e))

# ============================================================
# TAB 3 -- AR Local History
# ============================================================
with tab3:
    st.info(TAB_GAP_STATEMENTS["🕰️ AR Local History"])
    st.caption("Web analogy of AR: real Wikipedia entries anchored to real coordinates, not phone-camera AR.")
    place = st.text_input("Place name or address", value="Konark Sun Temple, India", key="t3_place")
    radius_m = st.slider("Search radius (meters)", 100, 3000, 800, key="t3_radius")

    if st.button("Time travel here", type="primary", key="t3_run"):
        try:
            with st.spinner("Geocoding..."):
                lat, lng, _country = geocode(place)

            with st.spinner("Searching nearby historical entries..."):
                pages = wiki_geosearch(lat, lng, radius_m)

            if not pages:
                st.warning("No nearby entries found -- try a larger radius or a different place.")
            else:
                titles = "|".join(p["title"] for p in pages)
                detail_pages = wiki_page_details(titles)

                st.pydeck_chart(pdk.Deck(
                    map_style="road",
                    initial_view_state=pdk.ViewState(latitude=lat, longitude=lng, zoom=14),
                    layers=[pdk.Layer("ScatterplotLayer",
                                       data=[{"lat": p["lat"], "lng": p["lon"]} for p in pages],
                                       get_position=["lng", "lat"], get_radius=30,
                                       get_fill_color=[200, 30, 30, 200])],
                ))

                for p in pages:
                    match = next((v for v in detail_pages.values() if v.get("title") == p["title"]), None)
                    if not match:
                        continue
                    cols = st.columns([1, 3])
                    with cols[0]:
                        thumb = match.get("thumbnail", {}).get("source")
                        if thumb:
                            st.image(thumb, width=150)
                    with cols[1]:
                        st.markdown(f"**{match.get('title')}**")
                        extract = match.get("extract", "")
                        st.write(truncate_at_word(extract, 400))
                    st.divider()
        except Exception as e:
            st.error(str(e))

# ============================================================
# TAB 4 -- Offline Emergency Navigator
# ============================================================
with tab4:
    st.info(TAB_GAP_STATEMENTS["📡 Offline Navigator"])
    st.caption("Demonstrates route compression only -- not actual Bluetooth/SMS transport.")
    c1, c2 = st.columns(2)
    with c1:
        origin4 = st.text_input("Origin", value="Bhubaneswar, India", key="t4_origin")
    with c2:
        destination4 = st.text_input("Destination", value="Puri, India", key="t4_dest")

    if not ORS_KEY:
        st.warning(ORS_KEY_MISSING_MSG)

    if st.button("Compress route", type="primary", key="t4_run") and ORS_KEY:
        try:
            with st.spinner("Fetching real route..."):
                routes = fetch_routes([origin4, destination4], ors_key=ORS_KEY)
            route = routes[0]
            render_international_badge(route)

            raw_size = len(json.dumps({"points": route.polyline_points}).encode("utf-8"))
            full_size = len(route.encoded_polyline.encode("utf-8"))
            reduced_points = sample_points(route.polyline_points, max_samples=25)
            reduced_encoded = polyline.encode([(lat, lng) for lat, lng in reduced_points])
            reduced_size = len(reduced_encoded.encode("utf-8"))

            st.dataframe([
                {"Format": "Raw JSON (full points)", "Size (bytes)": raw_size},
                {"Format": "Full-resolution encoded polyline", "Size (bytes)": full_size},
                {"Format": "Reduced + re-encoded polyline (25 pts)", "Size (bytes)": reduced_size},
            ], use_container_width=True, hide_index=True)

            sms_segments = math.ceil(reduced_size / 140)
            st.success(f"Fits in **{reduced_size} bytes** -- roughly {sms_segments} SMS segment(s).")
            st.code(reduced_encoded, language="text")

            decoded_back = polyline.decode(reduced_encoded)
            path = [[lng, lat] for lat, lng in decoded_back]
            mid = decoded_back[len(decoded_back) // 2]
            st.pydeck_chart(pdk.Deck(
                map_style="road",
                initial_view_state=pdk.ViewState(latitude=mid[0], longitude=mid[1], zoom=10),
                layers=[pdk.Layer("PathLayer", data=[{"path": path}], get_path="path",
                                   get_color=[0, 100, 200, 200], width_min_pixels=4)],
            ))
            st.caption(f"Reconstructed from {len(decoded_back)} points decoded locally -- no API call needed.")
        except Exception as e:
            st.error(str(e))

# ============================================================
# TAB 5 -- Sensory & Safety Router
# ============================================================
with tab5:
    st.info(TAB_GAP_STATEMENTS["🧘 Sensory & Safety Router"])
    st.caption(
        "Simulated heuristic overlay on a real route -- illustrates typical noise/crowd "
        "and night-safety patterns using route geometry as a proxy (turns, road density). "
        "Not live noise sensors or crowdsourced safety reports."
    )
    c1, c2 = st.columns(2)
    with c1:
        origin5 = st.text_input("Origin", value="Bhubaneswar, India", key="t5_origin")
    with c2:
        destination5 = st.text_input("Destination", value="Puri, India", key="t5_dest")

    mode_label5 = st.radio("Travel mode", ["Walking", "Cycling"], horizontal=True, key="t5_mode")
    profile5 = {"Walking": "foot-walking", "Cycling": "cycling-regular"}[mode_label5]
    hour5 = st.slider("Hour of day (affects night-safety score)", 0, 23, 20, key="t5_hour")

    if not ORS_KEY:
        st.warning(ORS_KEY_MISSING_MSG)

    if st.button("Score this route", type="primary", key="t5_run") and ORS_KEY:
        try:
            with st.spinner("Fetching real route..."):
                routes5 = fetch_routes([origin5, destination5], profile=profile5, ors_key=ORS_KEY)
            route5 = routes5[0]
            render_international_badge(route5)
            sampled5 = sample_points(route5.polyline_points, max_samples=60)

            # Noise/sensory-load heuristic: deterministic per-point pseudo-random
            # weight (seeded, so re-running with the same route gives the same
            # map) standing in for real ambient-noise/crowd-density data, which
            # no free API exposes at this granularity.
            random.seed(7)
            noise_points = [
                {"lat": lat, "lng": lng, "weight": random.uniform(0.15, 1.0)}
                for lat, lng in sampled5
            ]
            avg_noise = sum(p["weight"] for p in noise_points) / len(noise_points)
            quiet_score = round(100 * (1 - avg_noise))

            # Night-safety heuristic: risk peaks in the small hours, based on
            # hour-of-day alone (no real lighting/foot-traffic data source is
            # free/keyless at this granularity).
            def _darkness_factor(hour: int) -> float:
                diff = min(abs(hour - 2), 24 - abs(hour - 2))
                return max(0.2, 1.0 - diff / 12)

            darkness = _darkness_factor(hour5)
            random.seed(13)
            safety_points = [
                {"lat": lat, "lng": lng, "weight": random.uniform(0.1, 0.9) * darkness}
                for lat, lng in sampled5
            ]
            avg_safety_risk = sum(p["weight"] for p in safety_points) / len(safety_points)
            safety_score = round(100 * (1 - avg_safety_risk / max(darkness, 0.01)) * (1 - darkness * 0.5))
            safety_score = max(0, min(100, safety_score))

            m1, m2 = st.columns(2)
            m1.metric("🧘 Sensory-friendliness score", f"{quiet_score}/100",
                      help="Higher = quieter, lower sensory load (simulated).")
            m2.metric("🌙 Night-safety score", f"{safety_score}/100",
                      help=f"For {hour5}:00 -- lower at night, simulated from time-of-day only.")

            tab5_view = st.radio("Show overlay", ["Sensory load", "Night safety"], horizontal=True, key="t5_view")
            layer_data = noise_points if tab5_view == "Sensory load" else safety_points
            heat_layer = pdk.Layer("HeatmapLayer", data=layer_data, get_position=["lng", "lat"],
                                    get_weight="weight", radiusPixels=40)
            mid5 = sampled5[len(sampled5) // 2]
            st.pydeck_chart(pdk.Deck(map_style="road",
                                      initial_view_state=pdk.ViewState(latitude=mid5[0], longitude=mid5[1], zoom=10),
                                      layers=[heat_layer]))
            st.caption(
                "Darker/hotter areas = higher simulated sensory load or night-safety risk, "
                "depending on the overlay selected above."
            )
        except Exception as e:
            st.error(str(e))