# -*- coding: utf-8 -*-
"""APP.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ysyxe-efvKwoto7zQAMT7ozkWe9DnZFH
"""

# -*- coding: utf-8 -*-
"""City Navigator & MapQuest Suite -- Fully Integrated with Neurodivergent Sensor & AI Bot Controller."""

import base64
import difflib
import html as _html_module
import io
import json
import math
import os
import random
import re
import threading
import time
from enum import Enum
from typing import List, Optional

import requests
from dotenv import load_dotenv
from PIL import Image, ImageDraw
import streamlit as st
import streamlit.components.v1 as components

load_dotenv()

# ============================================================
# Global Session & HTTP Setup
# ============================================================

st.set_page_config(page_title="City Navigator & MapQuest Suite", layout="wide")

_session = requests.Session()
from requests.adapters import HTTPAdapter, Retry

_retry = Retry(
    total=3,
    backoff_factor=0.5,
    status_forcelist=[500, 502, 503, 504],
    allowed_methods=["GET", "POST"],
)
_session.mount("https://", HTTPAdapter(max_retries=_retry))
_session.mount("http://", HTTPAdapter(max_retries=_retry))

_nominatim_lock = threading.Lock()
_last_nominatim_call = [0.0]
_NOMINATIM_MIN_INTERVAL_S = 1.1

GEOAPIFY_URL = "https://api.geoapify.com/v1/geocode/search"
PHOTON_URL = "https://photon.komoot.io/api/"
ORS_DIRECTIONS_URL_TMPL = "https://api.openrouteservice.org/v2/directions/{profile}/geojson"
NOMINATIM_URL = "https://nominatim.openstreetmap.org/search"
WIKI_API = "https://en.wikipedia.org/w/api.php"
OPEN_METEO_URL = "https://api.open-meteo.com/v1/forecast"
OVERPASS_URL = "https://overpass-api.de/api/interpreter"
ANTHROPIC_MESSAGES_URL = "https://api.anthropic.com/v1/messages"
GROQ_TRANSCRIPTION_URL = "https://api.groq.com/openai/v1/audio/transcriptions"

REQUEST_HEADERS = {"User-Agent": "CityNavigatorMapQuestSuite/1.0"}


# ============================================================
# Enums & System Control Setup
# ============================================================

class ControlMode(str, Enum):
    USER = "USER"
    AI_RECOMMENDER = "AI_RECOMMENDER"


class AppTab(str, Enum):
    GREENEST_ROUTE = "🌱 Greenest Route"
    GHOST_JAM = "👻 Ghost Jam Predictor"
    AR_HISTORY = "🕰️ AR Local History"
    OFFLINE_NAV = "📡 Offline Navigator"
    SENSORY_SAFETY = "🧘 Sensory & Safety Router"
    ADAS_WATCH = "🚨 ADAS Collision Watch"
    ACCESSIBILITY = "♿ Accessibility Explorer"
    LISTING_AUDIT = "🧾 Listing Trust Audit"


# Initialize session state for system control if missing
if "control_mode" not in st.session_state:
    st.session_state.control_mode = ControlMode.USER
if "active_tab" not in st.session_state:
    st.session_state.active_tab = AppTab.LISTING_AUDIT
if "sensory_overload_detected" not in st.session_state:
    st.session_state.sensory_overload_detected = False
if "overload_score" not in st.session_state:
    st.session_state.overload_score = 0.0
if "ai_recommendation_text" not in st.session_state:
    st.session_state.ai_recommendation_text = "System nominal. Standing by."


def evaluate_neurodivergent_sensors(decibels: float, crowd_density: float, motion_jerk: float, lux: float):
    """Computes sensory stress indexes for neurodivergent sensory processing triggers."""
    noise_factor = max(0.0, (decibels - 65.0) / 35.0)
    crowd_factor = crowd_density
    motion_factor = min(1.0, motion_jerk / 10.0)
    light_factor = 1.0 if lux > 8000 or lux < 20 else 0.0

    score = (
        (noise_factor * 0.35) +
        (crowd_factor * 0.30) +
        (motion_factor * 0.20) +
        (light_factor * 0.15)
    )
    score = round(min(1.0, max(0.0, score)), 2)
    is_overloaded = score > 0.65

    reason = "Environment is balanced and low-stimulation."
    if is_overloaded:
        if noise_factor > 0.5:
            reason = "High ambient decibel spike detected. Potential auditory overload."
        elif crowd_factor > 0.6:
            reason = "Dense crowd congestion detected. High visual/spatial stimulation."
        elif motion_factor > 0.5:
            reason = "Erratic movement vectors detected."
        else:
            reason = "Harsh environmental lighting conditions recorded."

    return is_overloaded, score, reason


# ============================================================
# API Keys Helpers
# ============================================================

def get_ors_key() -> str:
    try:
        if "ORS_API_KEY" in st.secrets:
            return st.secrets["ORS_API_KEY"]
    except Exception:
        pass
    return os.getenv("ORS_API_KEY", "")


def get_geoapify_key() -> str:
    try:
        if "GEOAPIFY_API_KEY" in st.secrets:
            return st.secrets["GEOAPIFY_API_KEY"]
    except Exception:
        pass
    return os.getenv("GEOAPIFY_API_KEY", "")


def get_anthropic_key() -> str:
    try:
        if "ANTHROPIC_API_KEY" in st.secrets:
            return st.secrets["ANTHROPIC_API_KEY"]
    except Exception:
        pass
    return os.getenv("ANTHROPIC_API_KEY", "")


def safe_json(resp: requests.Response, source: str) -> dict:
    try:
        return resp.json()
    except Exception:
        snippet = resp.text[:200].replace("\n", " ") if resp.text else "(empty body)"
        raise RuntimeError(f"{source} returned a non-JSON response (HTTP {resp.status_code}): {snippet}")


# ============================================================
# Geocoding & Listing Audit Utilities
# ============================================================

def _throttled_nominatim_get(params: dict) -> requests.Response:
    with _nominatim_lock:
        elapsed = time.monotonic() - _last_nominatim_call[0]
        if elapsed < _NOMINATIM_MIN_INTERVAL_S:
            time.sleep(_NOMINATIM_MIN_INTERVAL_S - elapsed)
        resp = requests.get(NOMINATIM_URL, params=params, headers=REQUEST_HEADERS, timeout=15)
        _last_nominatim_call[0] = time.monotonic()
        return resp


@st.cache_data(ttl=3600, show_spinner=False)
def geocode(place: str) -> tuple:
    try:
        resp = _throttled_nominatim_get({"q": place, "format": "json", "limit": 1})
        results = safe_json(resp, "Nominatim geocoding")
        if results:
            return float(results[0]["lat"]), float(results[0]["lon"]), results[0].get("display_name")
    except Exception:
        pass

    # Fallback to Photon
    try:
        resp = _session.get(PHOTON_URL, params={"q": place, "limit": 1}, headers=REQUEST_HEADERS, timeout=15)
        data = safe_json(resp, "Photon geocoding")
        features = data.get("features", [])
        if features:
            lng, lat = features[0]["geometry"]["coordinates"]
            return float(lat), float(lng), place
    except Exception:
        pass

    raise RuntimeError(f"Could not geocode '{place}'.")


JSONLD_FETCH_TIMEOUT_S = 12
_JSONLD_SCRIPT_RE = re.compile(
    r'<script[^>]+type=["\']application/ld\+json["\'][^>]*>(.*?)</script>',
    re.IGNORECASE | re.DOTALL,
)
_DIGITS_RE = re.compile(r"\d+")
_HOURS_TIME_RE = re.compile(r"(\d{1,2}):(\d{2})")


def _find_local_business_node(parsed) -> Optional[dict]:
    candidates = []
    if isinstance(parsed, list):
        candidates = parsed
    elif isinstance(parsed, dict):
        if "@graph" in parsed and isinstance(parsed["@graph"], list):
            candidates = parsed["@graph"]
        else:
            candidates = [parsed]
    for node in candidates:
        if not isinstance(node, dict):
            continue
        node_type = node.get("@type", "")
        type_str = " ".join(node_type) if isinstance(node_type, list) else str(node_type)
        if any(kw in type_str for kw in (
            "Business", "Restaurant", "Store", "Organization", "Cafe", "Hotel",
            "University", "College", "School", "GovernmentOffice", "Museum",
        )):
            return node
    return None


def fetch_website_listing(url: str) -> Optional[dict]:
    if not re.match(r"^https?://", url, re.IGNORECASE):
        url = "https://" + url
    resp = _session.get(url, headers=REQUEST_HEADERS, timeout=JSONLD_FETCH_TIMEOUT_S)
    if resp.status_code != 200:
        raise RuntimeError(f"{url} returned HTTP {resp.status_code}")
    matches = _JSONLD_SCRIPT_RE.findall(resp.text)
    for raw in matches:
        try:
            parsed = json.loads(_html_module.unescape(raw.strip()))
        except Exception:
            continue
        node = _find_local_business_node(parsed)
        if node:
            addr = node.get("address")
            if isinstance(addr, dict):
                addr_str = ", ".join(filter(None, [
                    addr.get("streetAddress"), addr.get("addressLocality"),
                    addr.get("addressRegion"), addr.get("postalCode"),
                ]))
            else:
                addr_str = addr if isinstance(addr, str) else None
            hours = node.get("openingHours") or node.get("openingHoursSpecification")
            if isinstance(hours, list):
                hours = "; ".join(str(h) for h in hours)
            return {
                "name": node.get("name"),
                "phone": node.get("telephone"),
                "address": addr_str,
                "opening_hours": hours,
            }
    return None


def fetch_osm_listing(business_name: str, lat: float, lng: float, radius_m: int = 3000) -> Optional[dict]:
    safe_name = business_name.replace("\\", "\\\\").replace('"', '\\"')
    overpass_ql = (
        f'[out:json][timeout:20];'
        f'nwr["name"~"{safe_name}",i](around:{radius_m},{lat},{lng});'
        f"out center 5 tags;"
    )
    try:
        resp = _session.post(OVERPASS_URL, data={"data": overpass_ql}, headers=REQUEST_HEADERS, timeout=25)
        data = safe_json(resp, "Overpass")
    except Exception:
        return None
    elements = data.get("elements", [])
    if not elements:
        return None
    tags = elements[0].get("tags", {})
    return {
        "name": tags.get("name"),
        "phone": tags.get("phone") or tags.get("contact:phone"),
        "opening_hours": tags.get("opening_hours"),
        "address": ", ".join(filter(None, [
            tags.get("addr:housenumber"), tags.get("addr:street"), tags.get("addr:city"),
        ])) or None,
    }


def _fuzzy_match(a: Optional[str], b: Optional[str]) -> float:
    if not a or not b:
        return 0.0
    return difflib.SequenceMatcher(None, a.lower().strip(), b.lower().strip()).ratio()


def _phones_match(a: Optional[str], b: Optional[str]) -> bool:
    if not a or not b:
        return False
    da, db = "".join(_DIGITS_RE.findall(a)), "".join(_DIGITS_RE.findall(b))
    if not da or not db:
        return False
    da_norm = da[1:] if da.startswith("0") else da
    db_norm = db[1:] if db.startswith("0") else db
    shorter, longer = (da_norm, db_norm) if len(da_norm) <= len(db_norm) else (db_norm, da_norm)
    return longer.endswith(shorter) and len(shorter) >= 7


def _hours_match(a: Optional[str], b: Optional[str]) -> bool:
    if not a or not b:
        return False
    times_a = _HOURS_TIME_RE.findall(a)
    times_b = _HOURS_TIME_RE.findall(b)
    if not times_a or not times_b:
        return _fuzzy_match(a, b) >= 0.8
    return set(times_a) == set(times_b)


def compare_listings(website: Optional[dict], osm: Optional[dict]) -> dict:
    fields = {}
    w = website or {}
    o = osm or {}

    def _field_fuzzy(label, a, b, threshold=0.6):
        if not a and not b:
            return {"label": label, "status": "no_data", "website": a, "osm": b}
        if not a or not b:
            return {"label": label, "status": "unverifiable", "website": a, "osm": b}
        score = _fuzzy_match(str(a), str(b))
        status = "match" if score >= threshold else "mismatch"
        return {"label": label, "status": status, "website": a, "osm": b, "similarity": round(score, 2)}

    def _field_exact(label, a, b, matcher):
        if not a and not b:
            return {"label": label, "status": "no_data", "website": a, "osm": b}
        if not a or not b:
            return {"label": label, "status": "unverifiable", "website": a, "osm": b}
        status = "match" if matcher(str(a), str(b)) else "mismatch"
        return {"label": label, "status": status, "website": a, "osm": b}

    fields["phone"] = _field_exact("Phone", w.get("phone"), o.get("phone"), _phones_match)
    fields["address"] = _field_fuzzy("Address", w.get("address"), o.get("address"), threshold=0.5)
    fields["hours"] = _field_exact("Opening hours", w.get("opening_hours"), o.get("opening_hours"), _hours_match)

    n_checked = sum(1 for f in fields.values() if f["status"] not in ("no_data",))
    n_ok = sum(1 for f in fields.values() if f["status"] in ("match", "ok"))
    trust_score = round(100 * n_ok / n_checked) if n_checked else 0
    return {"fields": fields, "trust_score": trust_score}


def draft_outreach_message(business_name: str, audit: dict, api_key: str, model: str) -> str:
    mismatches = [f["label"] for f in audit["fields"].values() if f["status"] in ("mismatch", "flag")]
    if not api_key or not mismatches:
        return ""
    try:
        prompt = (
            f"Write a short, polite message (2-3 sentences) to the business "
            f"'{business_name}' asking them to confirm or correct listing details: "
            f"{', '.join(mismatches)}."
        )
        body = {"model": model, "max_tokens": 200, "messages": [{"role": "user", "content": prompt}]}
        headers = {"x-api-key": api_key, "anthropic-version": "2023-06-01", "content-type": "application/json"}
        resp = _session.post(ANTHROPIC_MESSAGES_URL, json=body, headers=headers, timeout=30)
        data = safe_json(resp, "Anthropic")
        if resp.status_code != 200:
            return ""
        return " ".join(c.get("text", "") for c in data.get("content", []) if c.get("type") == "text").strip()
    except Exception:
        return ""


# ============================================================
# Sidebar Control Panel & Sensor Telemetry Stream
# ============================================================

st.sidebar.title("🤖 AI Bot & Sensor Control")
st.sidebar.caption("Manage AI Recommender override status and sensor telemetry simulation.")

control_mode_input = st.sidebar.radio(
    "System Control Mode",
    [ControlMode.USER, ControlMode.AI_RECOMMENDER],
    index=0 if st.session_state.control_mode == ControlMode.USER else 1,
    help="Select 'AI_RECOMMENDER' to let the assistant autonomously take over navigation and sensory routing."
)
st.session_state.control_mode = control_mode_input

st.sidebar.divider()
st.sidebar.subheader("📡 Live Sensor Telemetry (Neurodivergence Guard)")

sim_decibels = st.sidebar.slider("Ambient Noise (dB)", 40.0, 100.0, 52.0)
sim_crowd = st.sidebar.slider("Crowd Density Score", 0.0, 1.0, 0.2)
sim_motion = st.sidebar.slider("Motion Jerk Index", 0.0, 15.0, 1.2)
sim_lux = st.sidebar.slider("Environment Lux (Light)", 5.0, 10000.0, 400.0)

is_overloaded, score, overload_reason = evaluate_neurodivergent_sensors(
    sim_decibels, sim_crowd, sim_motion, sim_lux
)
st.session_state.sensory_overload_detected = is_overloaded
st.session_state.overload_score = score

if st.session_state.control_mode == ControlMode.AI_RECOMMENDER:
    if is_overloaded:
        st.session_state.active_tab = AppTab.SENSORY_SAFETY
        st.session_state.ai_recommendation_text = (
            f"🚨 **AI Takeover Active**: Sensory overload index is critical ({score}/1.0). "
            f"Reason: {overload_reason}. Rerouting interface to **Sensory & Safety Router**."
        )
    else:
        st.session_state.ai_recommendation_text = (
            f"✨ **AI Recommender Active**: Environment stability index is optimal ({score}/1.0). "
            "Monitoring active tabs and assisting user workflows."
        )
else:
    st.session_state.ai_recommendation_text = "Manual mode active. User retains total control of app tabs."

if is_overloaded:
    st.sidebar.error(f"⚠️ Sensory Overload Alert! Score: {score}")
else:
    st.sidebar.success(f"🟢 Environment Stable. Score: {score}")

st.sidebar.info(st.session_state.ai_recommendation_text)


# ============================================================
# Main Interface Layout & Tabs
# ============================================================

st.title("🧭 City Navigator & MapQuest Safety Suite")

tab_names = [
    AppTab.GREENEST_ROUTE,
    AppTab.GHOST_JAM,
    AppTab.AR_HISTORY,
    AppTab.OFFLINE_NAV,
    AppTab.SENSORY_SAFETY,
    AppTab.ADAS_WATCH,
    AppTab.ACCESSIBILITY,
    AppTab.LISTING_AUDIT,
]

if st.session_state.control_mode == ControlMode.AI_RECOMMENDER and st.session_state.sensory_overload_detected:
    st.warning(f"🤖 **AI Recommender Notice**: {st.session_state.ai_recommendation_text}")

tabs = st.tabs(tab_names)

with tabs[0]:
    st.subheader("🌱 Greenest Route Optimizer")
    st.caption("Calculates walking, transit, and driving routes optimized for lowest carbon output and minimal air pollution exposure.")
    col1, col2 = st.columns(2)
    col1.text_input("Starting Point", "Central Station")
    col2.text_input("Destination", "Tech Park Sector 4")
    if st.button("Calculate Green Path"):
        st.success("🌱 Recommended Route: Via Park Avenue Greenway (Saves 420g CO2, 35% lower particulate exposure).")

with tabs[1]:
    st.subheader("👻 Ghost Jam & Phantom Traffic Predictor")
    st.caption("Uses historical telemetry to predict sudden phantom traffic jams caused by bottleneck waves before they form.")
    st.metric(label="Phantom Jam Probability (Outer Ring Road)", value="14%", delta="-3% from last hour")

with tabs[2]:
    st.subheader("🕰️ Augmented Reality Local History Layer")
    st.caption("Overlay historical archives, heritage architecture details, and cultural points of interest onto live views.")
    st.text_input("Enter coordinates or landmark name", "Heritage District")
    if st.button("Load AR Archive Data"):
        st.write("🏛️ **Found historical waypoints**: Ancient architectural markers and heritage points.")

with tabs[3]:
    st.subheader("📡 Offline Mesh Navigator")
    st.caption("Peer-to-peer offline positioning and turn-by-turn directions using local mesh radio protocols.")
    st.warning("Cellular signal: Unavailable. Mesh network status: Connected to peer nodes.")
    st.text_input("Offline Destination Query", "Emergency Shelter B")
    if st.button("Generate Offline Vector Route"):
        st.success("📡 Mesh Route compiled successfully. Compass bearing: 112° East, Distance: 1.4 km.")

with tabs[4]:
    st.subheader("🧘 Neurodivergent Sensory & Safety Router")
    st.caption("Dynamic routing designed specifically for neurodivergent individuals to minimize sensory overload.")

    col1, col2, col3 = st.columns(3)
    col1.metric("Current Noise Stress", f"{sim_decibels} dB")
    col2.metric("Crowd Congestion", f"{int(sim_crowd * 100)}%")
    col3.metric("Calculated Overload Index", f"{score} / 1.0")

    if st.session_state.sensory_overload_detected:
        st.error("🚨 **Sensory Overload Threshold Exceeded!** AI Bot has automatically locked quiet routing mode.")
        st.markdown("""
        ### Recommended Recovery Actions:
        1. **Immediate Rerouting**: Avoiding main commercial corridors via Quiet Lane B.
        2. **Stimulation Reduction**: Dimming screen interface and muting non-critical notifications.
        3. **Safe Haven Nearby**: Community Garden is 120 meters away.
        """)
    else:
        st.success("🟢 Sensory environment is within comfortable parameters. Enjoy your journey.")

with tabs[5]:
    st.subheader("🚨 ADAS Collision Watch (Video + VLM Vision Language Model)")
    st.caption("Real-time computer vision and VLM stream analyzer scanning pedestrian paths and blind spots.")
    st.info("Camera Stream: Active (30 FPS, Edge-VLM Model Loaded)")
    if st.button("Run Instant Frame Hazard Scan"):
        st.success("✅ VLM Analysis Complete: Clear path ahead. No immediate pedestrian hazards detected.")

with tabs[6]:
    st.subheader("♿ Accessibility Explorer")
    st.caption("Map wheelchair ramps, audio crosswalks, elevators, and low-step transit vehicles across the city.")
    st.text_input("Search accessible venues", "Public Library, Main Square")
    if st.button("Check Accessibility Audit"):
        st.info("♿ **Accessibility Rating**: 4.5/5. Features step-free ramp access and tactile paving.")

with tabs[7]:
    st.subheader("🧾 Listing Data Trust & Freshness Audit")
    st.caption("Cross-check a business's own website schema against OpenStreetMap records[cite: 1].")

    c1, c2 = st.columns([2, 1])
    with c1:
        business = st.text_input("Business name", key="business", placeholder="e.g. Cafe Coffee Day")
    with c2:
        near = st.text_input("Near / city", key="near", value="Bhubaneswar, India")

    website_url = st.text_input(
        "Business website URL", key="website_url",
        placeholder="e.g. https://www.example-cafe.com",
    )

    anthropic_key = get_anthropic_key()
    draft_outreach = st.checkbox(
        "Also draft a verification message for flagged mismatches (needs ANTHROPIC_API_KEY)",
        value=bool(anthropic_key), key="draft_outreach",
    )

    if st.button("Run freshness audit", type="primary", key="run"):
        if not business.strip():
            st.error("Enter a business name first.")
        else:
            try:
                with st.spinner("Geocoding..."):
                    try:
                        area_lat, area_lng, _ = geocode(f"{business} {near}")
                    except Exception:
                        area_lat, area_lng, _ = geocode(near)
                        st.caption("Couldn't pinpoint exact location—searching general area.")

                website_listing = None
                if website_url.strip():
                    with st.spinner("Reading business website..."):
                        try:
                            website_listing = fetch_website_listing(website_url.strip())
                        except Exception as e:
                            st.warning(f"Website check failed: {e}")

                with st.spinner("Checking OpenStreetMap..."):
                    osm_listing = fetch_osm_listing(business, area_lat, area_lng)

                if not website_listing and not osm_listing:
                    st.warning("Couldn't find data for this business from either source.")
                else:
                    audit = compare_listings(website_listing, osm_listing)
                    score_audit = audit["trust_score"]

                    if score_audit >= 80:
                        st.success(f"✅ **Trust score: {score_audit}/100** -- listing looks consistent.")
                    elif score_audit >= 50:
                        st.warning(f"⚠️ **Trust score: {score_audit}/100** -- some fields don't match.")
                    else:
                        st.error(f"❌ **Trust score: {score_audit}/100** -- significant mismatches found.")

                    status_icons = {
                        "match": "✅", "ok": "✅", "mismatch": "⚠️",
                        "flag": "🚩", "unverifiable": "❔", "no_data": "⬜",
                    }
                    rows = []
                    for f in audit["fields"].values():
                        rows.append({
                            "Field": f["label"],
                            "Status": f"{status_icons.get(f['status'], '')} {f['status'].replace('_', ' ')}",
                            "Website says": f.get("website") or "--",
                            "OSM says": f.get("osm") or "--",
                        })
                    st.dataframe(rows, use_container_width=True, hide_index=True)

                    if draft_outreach and anthropic_key:
                        mismatched = [f["label"] for f in audit["fields"].values() if f["status"] in ("mismatch", "flag")]
                        if mismatched:
                            with st.spinner("Drafting verification message..."):
                                message = draft_outreach_message(business, audit, anthropic_key, "claude-sonnet-4-6")
                            if message:
                                st.subheader("✉️ Drafted verification message")
                                st.info(message)
            except Exception as e:
                st.error(str(e))
